### ISSUE TITLE
[Remote-Container Bug]: Opening the same Docker image as a different user closes the first running instance

### ISSUE THREAD

**Issue by GarbenTangheVintecc** [microsoft/vscode-remote-release#10078]
Let me tell the story, including the steps to reproduce the bug and some logs.

0. Some Context

We use a remote server that runs Ubuntu 22.04 and has 2 user accounts: user1 (UID=1001) and user2 (UID=1002).

Our codebase contains the following files:

```Dockerfile
# .devcontainer/Dockerfile
FROM ubuntu:22.04

# Create User
RUN useradd --create-home --user-group --uid 5000 user
ENV USER=user
USER user
WORKDIR /home/user

ENTRYPOINT [ "/usr/bin/bash" ]
```

```yaml
# .devcontainer/docker-compose.yaml
services:

  mono:
    image: mono_dev_x86_64_ubuntu_22.04
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: user
    volumes:
      - ..:/home/user/mono
    network_mode: host
```

```json
// .devcontainer/devcontainer.json
{
  "dockerComposeFile": "docker-compose.yaml",
  "name": "mono_test",
  "service": "mono",
  "updateRemoteUserUID": true,
  "workspaceFolder": "/home/user/mono"
}
```

1. What Works

My colleague (user1) connects with his Ubuntu 22.04 laptop through SSH with the server on his account.

```bash
$ id
uid=1001(user1) gid=1041(user1)
```

He opens our codebase in a devcontainer.

```bash
$ id
uid=1001(user) gid=1041(user)
```

_Note that the UID of the user inside the container updated correctly from 5000 to 1001._

2. What Does Not Work

I (user2) connect with my Ubuntu 24.04 laptop through SSH with the same server but on my account.

```bash
$ id
uid=1002(user2) gid=1042(user2)
```

I also open a devcontainer but starting from my copy of the codebase.

```bash
$ id
uid=1002(user) gid=1042(user)
```

_Note that the UID of the user inside the container updated correctly from 5000 to 1002._

My colleague now sees this pop-up on his open VS Code window.
![image](https://github.com/user-attachments/assets/ffc59138-7a6a-4925-8ee6-396de8a33b15)

When he reloads the window, the ID in his container changed to mine:

```bash
$ id
uid=1002(user) gid=1042(user)
```

We only see one container running, so he effectively connected with my running container.
His container is closed. This is problematic because my colleague loses all his work in the original devcontainer, as soon as I try to open the same container from my copy of the codebase.

- VSCode Version: 1.91.0
- Local OS Version: Ubuntu 22.04/24.04 LTS
- Remote OS Version: Ubuntu 22.04 LTS
- Remote Extension/Connection Type: Containers
- Remote SSH Version: 0.112.0

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Related to #8974, #7738, #7068, #2677, and #2456.
