### ISSUE TITLE
remote - container hangs when service doesn't exist

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-release#102]
User scenario from PyCon...

- use a `devcontainer.json` that points to a  `docker-compose.yml` that starts up multiple images
- in `devcontainer.json`, have an incorrect `service`, something that simply doesn't exist
- try to open the folder in a dev container

result: hang trying to connect to the dev container

expected: error in `devcontainer.json` that the service doesn't exist in `docker-compose.yml` would be great, but would suffice with a timeout that had a helpful error such as `Cannot connect to service: foo, please check devecontainer.json` or something like that.

**Comment by AngellusMortis** [comment]
So I am actually the person you talk to about this. I also discovered a similar issue related to this (can created a seperate issue, if you do not want to handle it as part of this one). 

If you are running multiple containers with the same service name with `docker-compose` from two different `docker-compose.yml` files in two different folders, VS Code _maybe_ attempt to connect to the wrong one. 

`~/dev/project1/docker-compose.yml`
```yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
version: '2.1'
```

`~/dev/project2/docker-compose.yml`
```yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
version: '2.1'
```

`~/dev/project2/.devcontainer/devcontainer.json`
```json
{
    "dockerComposeFile":  "../docker-compose.yml",
    "service": "web",
}
```

If you `docker-compose up` on `project1` and then open `Open Folder in Container...` in side of VS Code for `project2`, it can accidently connect to the `web` container for `project1`.
