### ISSUE TITLE
devcontainer does not map blobfuse data

### ISSUE THREAD

**Issue by JackCaster** [microsoft/vscode-remote-release#10292]
- VSCode Version: 1.93.1
- Local OS Version:  Ubuntu 20.04.6 LTS
- Remote OS Version: Ubuntu 20.04.6 LTS
- Remote Extension/Connection Type: Containers/WSL

I mounted an Azure blob in my Linux system via [blobfuse2](https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy?tabs=Ubuntu). After that, I can see the content of the Azure blobstorage in my local workspace. But when I start the devcontainer in that workspace, the content of the blobfuse disappears. The only way to get the blobfuse content in the devcontainer is to rebuild the container. Similarly, if I unmount the blobfuse in the host, the content will still be visible in the devcontainer until a rebuilt. In summary, the devcontainer does not map (nor update) a blobfuse mount correctly.

It used to work few months ago, but I cannot remember what version of vscode/blobfuse I used. Since then, there have been few updates.

Steps to Reproduce:

1. Mount a blobstorage with blobfuse2 in the workspace `blobfuse2 mount <...> --config-file=<...>` where the config file is something like
```yaml
allow-other: true 

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: <temp path>
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <...>
  container: <...>
  mode: sas 
```
2. Start the devcontainer in that workspace
3. All folders in the workspace will be mounted correctly, but the blobfuse one will not be updated correctly. 

Does this issue occur when you try this locally?: No, the blobfuse folder is mounted correctly
Does this issue occur when you try this locally and all extensions are disabled?: No

Related to issue https://github.com/Azure/azure-storage-fuse/issues/1522
