### ISSUE TITLE
Unable to Resolve ${localEnv:FOO} in DevContainer with WSL

### ISSUE THREAD

**Issue by jang2162** [microsoft/vscode-remote-release#10530]
I attempted to set a token as an environment variable and pass it to the DevContainer, but the token value is not being recognized inside the container.

Configuration Details:

- devcontainer.json 
   ```json
   {
	  "name": "Base Dev Container",
	  "dockerComposeFile": "./vscode/docker-compose.yml",
	  "service": "app",
	  "forwardPorts": ["nginx:80", "mysql:3306", "redis:6379"],
	  "postCreateCommand": "cd ${localWorkspaceFolder} && bash ./.devcontainer/postCreateCommand.sh",
	  "containerEnv": {
		"NPM_TOKEN": "${localEnv:NPM_TOKEN}",
		"TEST1": "${localEnv:NPM_TOKEN}",
		"TEST2": "${NPM_TOKEN}"
	  },
	  "remoteEnv": {
		"TEST3": "${containerEnv:NPM_TOKEN}",
		"TEST4": "${localEnv:NPM_TOKEN}",
		"TEST5": "${NPM_TOKEN}"
	  }
	}
   ```
- docker-compose.yml
   ```yml
   services:
	  app:
		build:
		  context: ../images/app
		  dockerfile: Dockerfile
		volumes:
		  - pnpm-store:/root/.local/share/pnpm/store
		  - nginx-config:/root/nginx-config
		environment:
		  TEST6: ${NPM_TOKEN}
		command: /bin/sh -c "while sleep 1000; do :; done"
	  nginx:
		build:
		  context: ../images/nginx
		  dockerfile: Dockerfile
		volumes:
		  - nginx-config:/etc/nginx/conf.d
	  mysql:
		image: mysql:8.4.3
		environment:
		  MYSQL_ROOT_PASSWORD: root
		  MYSQL_DATABASE: base
		  MYSQL_USER: base
		  MYSQL_PASSWORD: base
		volumes:
		  - mysql-data:/var/lib/mysql
	  redis:
		image: redis:7.4.1
		volumes:
		  - redis-data:/data
	volumes:
	  mysql-data:
	  nginx-config:
	  redis-data:
	  pnpm-store:
   ```

Testing Attempts:
I tested various methods to pass the environment variable in the configuration files, but all attempts failed.

Command:
`env | grep TEST`

Result:
```
TEST3=
TEST2=
TEST1=
TEST6=
TEST5=${NPM_TOKEN}
TEST4=
```

When checking the environment variables in the local terminal of VS Code, they are successfully retrieved.

`echo %NPM_TOKEN%`
`wsl -e /bin/sh -c "echo $NPM_TOKEN"`

---

- VSCode Version: 1.95.3
- Local OS Version: Windows 11 Pro 24H2 26100.2454
- Remote OS Version: Ubuntu 24.04.1 LTS
- Remote Extension/Connection Type: WSL and DevContainer

- Logs:
[devcontainer.log](https://github.com/user-attachments/files/18004607/devcontainer.log)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: (Except Devcontainer Extention) Yes
