### ISSUE TITLE
X applications can not start in devcontainer under Xwayland because of missing X authentication

### ISSUE THREAD

**Issue by nE0sIghT** [microsoft/vscode-remote-release#10791]
## Issue description

Running X application in a devcontainer works well when vscode is started under Xorg. However when running under Wayland (GNOME Mutter in my case) with Xwayland X applications doesn't start with error:

```
Authorization required, but no authorization protocol specified

Error: Can't open display: :0
```

I think vscode should use data from $XAUTHORITY variable to configure devcontainer. It looks like vscode do some steps to pass X auth data in the devcontainer because it works out of the box.

##  Steps to reproduce

1. git clone https://github.com/nE0sIghT/devcontainer-xauthority
2. Open cloned folder in the vscode 
3. Reopen workspace in the devcontainer
4. Open terminal in the vscode
5. Run `xclock`

## Actual results

xclock window appears when vscode started under Xorg.

`Authorization required` error when vscode started under Wayland.

## Expected results

xclock window should appear.

## Workarounds

- Run `xauth add` in the devcontainer with the data from host's `xauth list`
- Or run `xhost +local:docker` in the host which is less secure IMO

**Comment by jealescockie** [comment]
kkk

**Comment by nE0sIghT** [comment]
Any way to workaround this maybe with `initializeCommand`? Is there any way to save output of `initializeCommand`?

**Comment by basvd** [comment]
I have a solution/workaround using `initializeCommand`. The script will find the Xauthority/Xwaylandauth file in `XDG_RUNTIME_DIR` and create a copy with a known filename (e.g. `.devcontainer.Xauthority`) in the same directory. This file is then mounted into the container.

I've attached my solution below. Note: It is specific to my use-case, so take it as an example. The main purpose of my script was to support both WSL and Linux with GUI forwarding. This is done by generating a .env file based on the host environment. I later adapted this to work around the X auth problem as well. I also use a compose file as part of the solution, but maybe it can be done without one.

<details>
<summary>generate_env.sh</summary>

```bash
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

# Detect WSL from host context where this script runs (initializeCommand).
if [[ -n "${WSL_DISTRO_NAME:-}" ]] || grep -qi microsoft /proc/sys/kernel/osrelease 2>/dev/null; then
  cat >"${ENV_FILE}" <<EOF
# Auto-generated by .devcontainer/generate_env.sh (WSL)
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0
XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
PULSE_SERVER=/mnt/wslg/PulseServer
X11_SOCKET_DIR=/run/desktop/mnt/host/wslg/.X11-unix
WSLG_MOUNT_SOURCE=/run/desktop/mnt/host/wslg
XAUTHORITY_PATH=/mnt/wslg/runtime-dir/.Xauthority
EOF
else
  display="${DISPLAY:-}"
  wayland_display="${WAYLAND_DISPLAY:-wayland-0}"
  xdg_runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
  pulse_server="${PULSE_SERVER:-}"
  xauthority_path="${XAUTHORITY:-}"
  xauthority_stable_path=""

  # Create a stable Xauthority copy next to the current authority file.
  if [[ -z "${xauthority_path}" ]]; then
    if [[ -f "${xdg_runtime_dir}/.Xauthority" ]]; then
      xauthority_path="${xdg_runtime_dir}/.Xauthority"
    else
      for xauthority_path in "${xdg_runtime_dir}"/.mutter-Xwaylandauth.*; do
        if [[ -f "${xauthority_path}" ]]; then
          break
        fi
        xauthority_path=""
      done
    fi
  fi

  if [[ -n "${xauthority_path}" ]] && [[ -f "${xauthority_path}" ]]; then
    xauthority_dir="$(dirname "${xauthority_path}")"
    xauthority_stable_path="${xauthority_dir}/.devcontainer.Xauthority"
    cp -f "${xauthority_path}" "${xauthority_stable_path}"
    chmod 600 "${xauthority_stable_path}" 2>/dev/null || true
  fi

  {
    echo "# Auto-generated by .devcontainer/generate_env.sh (Linux)"
    if [[ -n "${display}" ]]; then
      echo "DISPLAY=${display}"
    fi
    echo "WAYLAND_DISPLAY=${wayland_display}"
    echo "XDG_RUNTIME_DIR=${xdg_runtime_dir}"
    if [[ -n "${pulse_server}" ]]; then
      echo "PULSE_SERVER=${pulse_server}"
    fi
    echo "X11_SOCKET_DIR=/tmp/.X11-unix"
    echo "WSLG_MOUNT_SOURCE=/tmp"
    if [[ -n "${xauthority_stable_path}" ]]; then
      echo "XAUTHORITY_PATH=${xauthority_stable_path}"
    fi
  } >"${ENV_FILE}"
fi
``` 
</details>

<details>

<summary>compose.yaml</summary>

```yaml
    env_file:
      - .env
    volumes:
      - ..:/workspace:cached
      # Optional WSLg mount point
      - ${WSLG_MOUNT_SOURCE:-/tmp}:/mnt/wslg
      # Optional X11/XWayland socket directory from host
      - ${X11_SOCKET_DIR:-/tmp/.X11-unix}:/tmp/.X11-unix
      # Optional Xauthority cookie for X11 auth
      - ${XAUTHORITY_PATH:-/dev/null}:/tmp/.Xauthority:ro
      # Wayland socket from host runtime dir to a stable path in container
      - ${XDG_RUNTIME_DIR:-/run/user/1000}/${WAYLAND_DISPLAY:-wayland-0}:/run/user/1000/${WAYLAND_DISPLAY:-wayland-0}
    environment:
      # GUI integration
      DISPLAY: ${DISPLAY:-:1}
      XAUTHORITY: /tmp/.Xauthority
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-wayland-0}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR:-/run/user/1000}
      PULSE_SERVER: ${PULSE_SERVER:-/mnt/wslg/PulseServer}
```

</details>
