### ISSUE TITLE
.devcontainer.json lacks docker-compose.override.yml support

### ISSUE THREAD

**Issue by jonfen** [microsoft/vscode-remote-release#1080]
https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

Per the docker documentation, given a `docker-compose.yml` and `docker-compose.override.yml` that reference the same service but *different* Dockerfiles...

### Current Behavior:
Empty array for "dockerComposeFile" in .devcontainer.json results in `docker-compose -f docker-compose.yml up`

### Ideal Behavior:
Empty array for "dockerComposeFile" in .devcontainer.json results in `docker-compose up`

### Given

**docker-compose.yml**
```
services:
  ubuntu-test:
    build:
      context: .
      dockerfile: base.Dockerfile
version: '3.7'
```

**docker-compose.override.yml**
```
services:
  ubuntu-test:
    build:
      context: .
      dockerfile: override.Dockerfile
version: '3.7'
```

### Tests

**$ docker-compose config**
```
services:
  ubuntu-test:
    build:
      context: /home/jonfen/docker-compose-override-test
      dockerfile: override.Dockerfile
version: '3.7'
```

**$ docker-compose -f docker-compose.override.yml -f docker-compose.yml config**
```
services:
  ubuntu-test:
    build:
      context: /home/jonfen/docker-compose-override-test
      dockerfile: base.Dockerfile
version: '3.7'
```

**$ docker-compose -f docker-compose.yml -f docker-compose.override.yml config**
```
services:
  ubuntu-test:
    build:
      context: /home/jonfen/docker-compose-override-test
      dockerfile: override.Dockerfile
version: '3.7'
```

References:
https://aka.ms/vscode-remote/devcontainer.json
