### ISSUE TITLE
Git doesn't detect modified files inside container

### ISSUE THREAD

**Issue by kevinfaguiar** [microsoft/vscode-remote-release#1827]
- VSCode Version: 
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-19-generic
```
- Local OS Version: Kubuntu 19.10
- Remote OS Version: node:10 Dockerfile
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Have a Git repo who has two submodules: API and UI:
<img src="https://i.imgur.com/hTwn6UF.png"/>

2. Create a .devcontainer.json file in both submodules with a content like:

```json

{
  "name": "API",
  "dockerComposeFile": [
    "../docker-compose.yml" // this docker-compose file location is at root folder of the parent project which has the two submodules (API and UI)
  ],
  "service": "api-service",
  "extensions": [
    "dbaeumer.vscode-eslint"
  ],
  "shutdownAction": "none",
  "workspaceFolder": "/usr/src/api-project",
  "postCreateCommand": "mkdir -p /root/.ssh && cp -r /root/.ssh-localhost/* /root/.ssh && chmod 700 /root/.ssh && chmod 600 /root/.ssh/* && chmod 777 /usr/src/*"
}

```

3. Imagine the docker-compose file is like that:
```yaml
version: "3"
services:
  api-service:
    build: api-project/
    ports:
      - "3001:3001"
    volumes:
      - /usr/src/api-project/node_modules
      - ./.git/.:/usr/src/.git
      - ./api-project:/usr/src/api-project/
      - ~/.ssh:/root/.ssh-localhost:ro
    command: npm run start:dev

  ui-service:
    build: ui-project/
    ports:
      - "3002:3002"
    volumes:
      - /usr/src/ui-project/node_modules
      - ./.git/.:/usr/src/.git
      - ~/.ssh:/root/.ssh-localhost:ro
      - ./ui-project:/usr/src/ui-project/
    depends_on:
      - api
    command: npm run start:dev
```

---

Description of the problem: 
- When i open any of the submodule folders, it prompts to open it in a container since it identified a devcontainer.json file, so i click yes
- It lift the docker-compose and open vscode inside the service container, as expected. I can use bash, edit files through vscode as expected, run npm install *somelib*
- The problem: when I edit a file and save it, it should appear in the Source Control vscode tab as a modified file, right? However this doesn't occur...
- If I run `git ls-files -m` inside the bash from the container at the project folder it doesn't detect the edited filed too...
- Also, if I edit the file with vscode INSIDE the container and open another vscode window, then OUTSIDE the container, git detects the modified files.

---

Does this issue occur when you try this locally?: No, only when using inside container with VS Code Remote - Containers extension
