### ISSUE TITLE
remote wsl2 + remote docker container

### ISSUE THREAD

**Issue by Gepar** [microsoft/vscode-remote-release#2395]
Hello.
Can we use both plugins (wsl2 and remote container) on the same time?
I understand that docker is work under wsl2, but i'll try to explain on example.
(Sorry for my bad english.)

I try to run postgres container on windows with docker-compose:
```
version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            # cause error on windows fs:
            #"changing permissions of '/var/lib/postgresql/data': Operation not permitted"
            - ./postgres-data:/var/lib/postgresql/data 
```

If i run in **wsl2** fs docker-compose file with volume mapping like this - it would work fine.

If i run in clear windows fs docker-compose with same volume mapping - it would crash with error:
> chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted

So ... i want to run docker-compose under wsl but if i'll open project in vscode on wsl fs plugin "remote container" will be disabled.
The most i can it's attach from vscode to running container, but than i'll lost functionality from devcontainer.json where i can configure plugins, evnironment and so on.
