### ISSUE TITLE
Add ability to specify container name in `devcontainer.json`

### ISSUE THREAD

**Issue by lugehorsam** [microsoft/vscode-remote-release#2485]
It would be great to be able to specify a default container name rather than the autogenerated name provided via VSCode.

I could rename the container afterwards but without knowing what the name of the container will be when first generated, it's non-trivial to automate this.

My use case is knowing the name of my development container so I can use `volumes-from` to pass its volumes to any new containers it creates.

**Comment by 1st** [comment]
In the `docker-compose.yml` I set the `container_name: XXX` setting and my container is named `XXX` in such case.

I just curious now, why VS Code auto-generates the group for containers automatically, like `{FolderName}_devcontainer`

**Comment by PavelSosin-320** [comment]
Container group name is metadata. Container metadata is passed to the Docker via labels. labels can be passed to the Docker engine using runArgs[]. The Container name is not metadata - this is DNS name of the container on the Corresponding Docker network and meaningful display value for the individual container.

**Comment by kosalanuwan** [comment]
Is there a way to leverage the docker compose `project-name` (now called top-level `name`) as for the devcontainer group name?

```yml
# docker-compose.yml
name: sql-server
services:
  az-sql:
      container_name: azure-sql
      image: mcr.microsoft.com/azure-sql-edge:latest
  
      ports:
        - 1433:1433
      
      volumes:
        - sql-data:/data

volumes:
  sql-data:
    name: sql-data
```
The `name: sql-server` is now used as the container group name with the docker compose v2.3.3. Previously in docker, this is the folder name. So the question is how do I leverage this when using .devcontainer.json instead of passing via `runArgs: []`?

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/958227/158561560-703aa596-93de-4291-a51f-b264d19312e8.png">
