### ISSUE TITLE
Remote-Containers: can't bind home (~) using long volume syntax

### ISSUE THREAD

**Issue by StevenLiekens** [microsoft/vscode-remote-release#2642]
When using Docker dev containers, some bind mounts break when using the [long syntax](https://docs.docker.com/compose/compose-file/#long-syntax).

An example using `'~'` to bind mount the home directory:

``` yaml
    volumes:
      # this works
      - ~:/home-bind-simple:cached

      # this doesn't
      - type: bind
        source: "~"
        target: /home-bind-extended
        consistency: cached
```

- VSCode Version: 1.43.2
- OS Version: Microsoft Windows [Version 10.0.18363.720]

Steps to Reproduce:

1. Clone https://github.com/StevenLiekens/devcontainer-host-home
2. Open folder in VS Code
3. Install extension: _ms-vscode-remote.remote-containers_
4. Reopen folder in container
5. Open terminal
6. `$ ls -la /home-bind-simple`
7. `$ ls -la /home-bind-extended`

The output of 6 and 7 should both list the contents of your home directory. Step 7 fails on my machine.

Does this issue occur when all extensions are disabled?: Yes
