### ISSUE TITLE
Can't open folder in container using docker-compose

### ISSUE THREAD

**Issue by holms** [microsoft/vscode-remote-release#2678]
![screen](https://user-images.githubusercontent.com/280958/78142458-a1829600-7435-11ea-8fbb-08ac328b28e7.png)

There's some kind of problem going on in here.

```
holms@debian ~> docker-compose --version
docker-compose version 1.25.4, build 8d51620a
holms@debian ~> code-insiders --version
1.44.0-insider
20b88fa0694cae8e46ffd305a1450ba58ae6065b
x64
```

Plugin version is latest.

Launching that particular command manually gives me this, as you can see there's no even error in here. So vscode trying to execute something that not supposed to work I guess.

```
holms@debian ~/D/c/s/a/.devcontainer> docker-compose -f /home/holms/Dev/contracts/xxx/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/xxx/app-prebid-config/.devcontainer/docker-compose.extend.yml  config ---services
Validate and view the Compose file.

Usage: config [options]

Options:
    --resolve-image-digests  Pin image tags to digests.
    --no-interpolate         Don't interpolate environment variables
    -q, --quiet              Only validate the configuration, don't print
                             anything.
    --services               Print the service names, one per line.
    --volumes                Print the volume names, one per line.
    --hash="*"               Print the service config hash, one per line.
                             Set "service1,service2" for a list of specified services
                             or use the wildcard symbol to display all services
```

**Comment by holms** [comment]
@Chuxel

Whole log from vscode window:

```
[0 ms] Start: Resolving remote
[2 ms] Setting up container for folder or workspace: /home/holms/Dev/contracts/setupad/app-prebid-config

[16 ms] Start: Check Docker is running
[16 ms] Start: Run: docker info
[171 ms] Start: Run: docker-compose version --short
[920 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=app-prebid-config --filter label=com.docker.compose.service=app-prebid-config
[973 ms] Start: Run: docker inspect --type container 5d5681bf0bc6
[1024 ms] Start: Run: docker-compose -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml config --services
[1741 ms] Command failed: docker-compose -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml config --services
```

Then I've tried to enter same command with local paths and it works

```
holms@debian ~/D/c/s/app-prebid-config> docker-compose -f docker-compose.yml -f .devcontainer/docker-compose.extend.yml config --services
traefik
aerospike
redis
app-prebid-config
```

Here's devcontainer.json

```
holms@debian ~/D/c/s/app-prebid-config> cat .devcontainer/devcontainer.json 
{
    "name": "app-prebid-config",
  
    // The order of the files is important since later files override previous ones
    "dockerComposeFile": ["../docker-compose.yml", "docker-compose.extend.yml"],
  
    "service": "app-prebid-config",
    "workspaceFolder": "/workspace",
    "shutdownAction": "stopCompose"
  }
```

**Comment by holms** [comment]
Same command with full paths doesn't work:

holms@debian ~/D/c/s/app-prebid-config> docker-compose -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml  config ---services
Validate and view the Compose file.
```
Usage: config [options]

Options:
    --resolve-image-digests  Pin image tags to digests.
    --no-interpolate         Don't interpolate environment variables
    -q, --quiet              Only validate the configuration, don't print
                             anything.
    --services               Print the service names, one per line.
    --volumes                Print the volume names, one per line.
    --hash="*"               Print the service config hash, one per line.
                             Set "service1,service2" for a list of specified services
                             or use the wildcard symbol to display all services
```

**Comment by Chuxel** [comment]
@chrmarti It looks like `"service": "app-prebid-config",` results in `--services` with nothing after it.  Any ideas?  Bug?

**Comment by holms** [comment]
I'll also add extended compose file:

```
holms@debian ~/D/c/s/app-prebid-config> cat .devcontainer/docker-compose.extend.yml 
version: '3.7'
services:
  app-prebid-config:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```
