### ISSUE TITLE
Can't rebuild a container

### ISSUE THREAD

**Issue by holms** [microsoft/vscode-remote-release#2681]
- VSCode Version: 1.44.0-insider
- Local OS Version: Debian 10.3
- Remote OS Version: golang docker image
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Modified Dockerfile and docker-compose.extend.yml for adding a port
2. Opened editor with same docker workspace
3. It's starting a container, then throws at me a pop-up saying "You need to rebuild a container"
4. Pushed a button to rebuild a container, then it reloaded workspace and same stuff happening in circles, starting again container, again same pop-up. so does that button even works..? or you have cached docker image?     I'm  not sure what's going on.

Does this issue occur when you try this locally?: Yes

Rebuilding container from cli is not an option, because compose can't find Вockerfile when I'm in .devcontainer, tried this command
```
holms@debian ~/D/c/s/a/.devcontainer> docker-compose -f ../docker-compose.yml -f ./docker-compose.extend.yml build app-prebid-config
Building app-prebid-config
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by chrmarti** [comment]
Could you attach the Dockerfile and docker-compose files?

**Comment by holms** [comment]
@chrmarti sorry for disappearance.

Here you go:

Short version of docker-compose.yml:

```
    app-prebid-config:
        container_name: app-prebid-config
        build:
            context: app
            target: dev
        environment:
            AEROSPIKE_HOST: aerospike
            AEROSPIKE_PORT: 3000
        depends_on:
            - redis
            - aerospike
            - traefik
        volumes:
            - ./app:/app/prebid-config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.core.rule=Host(`app-prebid-config.docker.localhost`)"
        
```

File list of .devcontainer folder:
```
holms@debian ~/D/c/s/app-prebid-config> tree .devcontainer/
.devcontainer/
├── devcontainer.json
├── docker-compose.extend.yml
└── Dockerfile
```

Here's docker-compose.extend.yml 

```
version: '3.7'
services:
  app-prebid-config:
    build: .
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ./app:/workspace:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 8080

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```

Here's Dockerfile of same folder:

```

FROM golang:1

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# This Dockerfile adds a non-root user with sudo access. Use the "remoteUser"
# property in devcontainer.json to use it. On Linux, the container user's GID/UIDs
# will be updated to match your local UID/GID (when using the dockerFile property).
# See https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Configure apt, install packages and tools
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \
    #
    # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
    && apt-get -y install git iproute2 procps lsb-release \
    #
    # Install Go tools w/module support
    && mkdir -p /tmp/gotools \
    && cd /tmp/gotools \
    && GO111MODULE=on go get -v golang.org/x/tools/gopls@latest 2>&1 \
    && GO111MODULE=on go get -v \
        honnef.co/go/tools/...@latest \
        golang.org/x/tools/cmd/gorename@latest \
        golang.org/x/tools/cmd/goimports@latest \
        golang.org/x/tools/cmd/guru@latest \
        golang.org/x/lint/golint@latest \
        github.com/mdempsky/gocode@latest \
        github.com/cweill/gotests/...@latest \
        github.com/haya14busa/goplay/cmd/goplay@latest \
        github.com/sqs/goreturns@latest \
        github.com/josharian/impl@latest \
        github.com/davidrjenni/reftools/cmd/fillstruct@latest \
        github.com/ramya-rao-a/go-outline@latest  \
        github.com/acroca/go-symbols@latest  \
        github.com/godoctor/godoctor@latest  \
        github.com/rogpeppe/godef@latest  \
        github.com/zmb3/gogetdoc@latest \
        github.com/fatih/gomodifytags@latest  \
        github.com/mgechev/revive@latest  \
        github.com/go-delve/delve/cmd/dlv@latest 2>&1 \
    #
    # Install Go tools w/o module support
    && go get -v github.com/alecthomas/gometalinter \
        github.com/uudashr/gopkgs/cmd/gopkgs 2>&1 \
    #
    # Install gocode-gomod
    && go get -x -d github.com/stamblerre/gocode 2>&1 \
    && go build -o gocode-gomod github.com/stamblerre/gocode \
    && mv gocode-gomod $GOPATH/bin/ \
    #
    # Install golangci-lint
    && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 2>&1 \
    #
    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
    && groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # [Optional] Add sudo support
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    # Add write permission for /go/pkg
    && chmod -R a+rwX /go/pkg \
    #
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* /go/src /tmp/gotools

# Update this to "on" or "off" as appropriate
ENV GO111MODULE=auto

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

```

**Comment by holms** [comment]
Here's also full log of vscode, as I've removed whole docker world and tried to build it again:

```
[0 ms] Start: Resolving remote
[2 ms] Setting up container for folder or workspace: /home/holms/Dev/contracts/setupad/app-prebid-config

[12 ms] Start: Check Docker is running
[809 ms] Start: Run: docker-compose -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml config --services
[1817 ms] Start: Run: docker-compose --project-name app-prebid-config -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml up -d --build
[2947 ms] Building app-prebid-config
[3282 ms] ERROR: Cannot locate specified Dockerfile: Dockerfile
[3385 ms] Failed: docker-compose up
[3392 ms] Command failed: docker-compose --project-name app-prebid-config -f /home/holms/Dev/contracts/setupad/app-prebid-config/docker-compose.yml -f /home/holms/Dev/contracts/setupad/app-prebid-config/.devcontainer/docker-compose.extend.yml up -d --build
```

**Comment by holms** [comment]
I think I've found what's the problem is, but I have no solution for it.

With this command you can see a config of two merged files and it seems to be build context is not overriden:

```
holms@debian ~/D/c/s/app-prebid-config> docker-compose  --project-name app-prebid-config -f docker-compose.yml -f .devcontainer/docker-compose.extend.yml  config
services:
  aerospike:
    container_name: aerospike
    image: aerospike:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.core.rule: Host(`aerospike.docker.localhost`)
    ports:
    - published: 3000
      target: 3000
    - published: 3001
      target: 3001
    - published: 3002
      target: 3002
    - published: 3003
      target: 3003
    volumes:
    - /home/holms/Dev/contracts/setupad/app-prebid-config/aerospike/aerospike.conf:/opt/aerospike/etc/aerospike.conf:rw
  app-prebid-config:
    build:
      context: /home/holms/Dev/contracts/setupad/app-prebid-config
      dockerfile: Dockerfile
      target: dev
    cap_add:
    - SYS_PTRACE
    command: /bin/sh -c "while sleep 1000; do:; done"
    container_name: app-prebid-config
    depends_on:
    - aerospike
    - redis
    - traefik
    environment:
      AEROSPIKE_HOST: aerospike
      AEROSPIKE_PORT: 3000
    labels:
      traefik.enable: "true"
      traefik.http.routers.core.rule: Host(`app-prebid-config.docker.localhost`)
    security_opt:
    - seccomp:unconfined
    volumes:
    - /home/holms/Dev/contracts/setupad/app-prebid-config/app:/app/prebid-config:rw
    - /home/holms/Dev/contracts/setupad/app-prebid-config/app:/workspace:cached
  redis:
    container_name: redis
    image: redis:latest
  traefik:
    command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --api.dashboard=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    container_name: traefik
    image: traefik:v2.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.docker.localhost`)
    ports:
    - published: 80
      target: 80
    - published: 8080
      target: 8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.7'


```
