### ISSUE TITLE
Honour the docker health status before connecting to the container

### ISSUE THREAD

**Issue by ttwd80** [microsoft/vscode-remote-release#2733]
This is my docker compose file:

```
version: "2.4"
services:
  golang:
    image: golang:1.14.2
    command: sh -c 'go get -v github.com/mdempsky/gocode github.com/uudashr/gopkgs/v2/cmd/gopkgs github.com/ramya-rao-a/go-outline golang.org/x/tools/gopls github.com/rogpeppe/godef golang.org/x/tools/cmd/goimports golang.org/x/lint/golint && go get -v github.com/go-delve/delve/cmd/dlv && echo Sleeping... & sleep infinity'''
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      network1:
        ipv4_address: 192.168.21.50
    environment: 
      - ENDPOINT_DYNAMODB=http://192.168.21.52:8000
      - ENDPOINT_REDIS_1=192.168.21.51:6379
    healthcheck:
      test: ["CMD", "dlv", "-version"]
      interval: 5s
      retries: 1200
  redis:
    image: redis:5.0.6
    networks:
      network1:
        ipv4_address: 192.168.21.51
  dynamo:
    image: amazon/dynamodb-local
    networks:
      network1:
        ipv4_address: 192.168.21.52
networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.21.0/24
``` 

Initially I didn't have `healthcheck` and `command` sections. Visual studio code prompted me with a message like this:
```
The "dlv" command is not available. Run "go get -v github.com/go-delve/delve/cmd/dlv" to install.
```

So I added the command section, to install `dlv` (and other tools) so I don't get prompted to install them. This works... some of the time.

The issue is, sometimes, I start the containers and use visual studio code to connect to them and `dlv` (or other tools) has not been installed yet, and I still get the prompt.

I added the `healthcheck` section and made `dlv` the last thing to install.

And I get something like:

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                             PORTS               NAMES
f8adfa9fb044        golang:1.14.2           "sh -c 'cd /go/src/g…"   14 seconds ago      Up 13 seconds (health: starting)                       docker_golang_1
fcbe29e3fa2d        redis:5.0.6             "docker-entrypoint.s…"   14 seconds ago      Up 13 seconds                      6379/tcp            docker_redis_1
64e29f526536        amazon/dynamodb-local   "java -jar DynamoDBL…"   14 seconds ago      Up 13 seconds                      8000/tcp            docker_dynamo_1
```

and

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                    PORTS               NAMES
f8adfa9fb044        golang:1.14.2           "sh -c 'cd /go/src/g…"   40 seconds ago      Up 39 seconds (healthy)                       docker_golang_1
fcbe29e3fa2d        redis:5.0.6             "docker-entrypoint.s…"   40 seconds ago      Up 39 seconds             6379/tcp            docker_redis_1
64e29f526536        amazon/dynamodb-local   "java -jar DynamoDBL…"   40 seconds ago      Up 39 seconds             8000/tcp            docker_dynamo_1
```

But I still get prompted if I  start using Visual Studio Code when the `health` status is not `healthy`.

The feature request is: when we try to connect to the docker container using `Remote-Containers: Attach to Running Container...`, it honours the container's health status (if health check was enabled).
