### ISSUE TITLE
Using docker-compose to debug .net core service errors out

### ISSUE THREAD

**Issue by JamesLoyd** [microsoft/vscode-remote-release#282]
- VSCode Version:  1.34.20-insider
- Local OS Version: Windows 10
- Remote OS Version: I assume its debian because I am using: mcr.microsoft.com/dotnet/core/sdk:2.2
- Remote Extension/Connection Type: SSH/Docker/WSL: Docker

Steps to Reproduce:

1. Create a docker-compose like so:
```
  inventorysapi:
    build:
      context: .
      dockerfile: Dockerfile-InventoryService
    volumes:
      - ..:/workspace
    # container_name: inventory-service
    # command: ["dotnet", "Inventory.API.dll"]
    networks:
      - back-tier
    ports: 
      - "5001:5001"      
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - back-tier
   
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back-tier
  dbconsumer:
    build:
      context: .
      dockerfile: Dockerfile-DbConsumer
    container_name: dbconsumer
    command: ["dotnet", "Consumer.dll"]
    networks:
      - back-tier

# Few other services are ommited
```
2. In Dockerfile-InventoryService
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2

# Install git, process tools
RUN apt-get update && apt-get -y install git procps

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
```
3. Click "Reopen in Container"
4. All goes file till: Run: docker exec
![image](https://user-images.githubusercontent.com/1821671/57541975-4ed05500-731e-11e9-9fd1-9e3ebe91e410.png)

I think its important to note that if I debug this in a dockerfile that it goes but fine. I have also tried using the example found here:
https://github.com/microsoft/vscode-dev-containers/tree/master/container-templates/docker-compose/.devcontainer

But I still run into issues.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

devcontainer.json
```
// See https://aka.ms/vscode-remote/containers for the
// documentation about the devcontainer.json format
{
	"dockerComposeFile": "docker-compose.yml",
	"service": "inventorysapi",
	"workspaceFolder": "/workspace",
	"shutdownAction": "stopCompose",
	"extensions": [
		"ms-vscode.csharp"
	]
}
```
