### ISSUE TITLE
appPort doesn't seem to allow connecting to port from browser

### ISSUE THREAD

**Issue by vnijs** [microsoft/vscode-remote-release#319]
- VSCode Version: 1.34.20 insider
- Local OS Version: macOS Mojave
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker running locally

Steps to Reproduce:

1. Start in vscode in some local directory with devcontainer.json as shown below. 
2. Trying to connect to 127.0.0.1:8989 in a browser shows "This page isn't working" although the output shown below seems fine. I also show a docker compose file below that, when run locally, does allow the user to connect to, for example, `http://localhost:8989` and see jupyterlab.

```
IP Address: 172.17.0.2
Extension host agent listening on 9753
--------------------------
Published Ports:
8080/tcp -> 127.0.0.1:8080
8765/tcp -> 127.0.0.1:8765
8787/tcp -> 127.0.0.1:8787
8989/tcp -> 127.0.0.1:8989
--------------------------

==> Received a management connection
==> Received an extension host connection.
==> Using UI language: en
==> Received a management connection
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**.devcontainer/devcontainer.json**
```
{
	"name": "rady-test",
	"image": "vnijs/rsm-msba",
	"workspaceFolder": "rady",
	"extensions": [
		"Ikuyadeu.r",
		"ms-python.python",
		"REditorSupport.r-lsp",
		"VisualStudioExptTeam.vscodeintellicode",
		"vscode-icons-team.vscode-icons",
	],
	"appPort": [
		"127.0.0.1:8080:8080",
		"127.0.0.1:8787:8787",
		"127.0.0.1:8989:8989",
		"127.0.0.1:8765:8765"
	]
}
```

**docker compose file that works as intended**
```
version: '3.5'
services:
  rsm-msba:
    image: "vnijs/rsm-msba"
    environment:
      SHELL: bin/bash
      PYTHONUSERBASE: /home/jovyan/.rsm-msba
      JUPYTER_PATH: /home/jovyan/.rsm-msba/share/jupyter
      JUPYTER_RUNTIME_DIR: /home/jovyan/.rsm-msba/share/jupyter/runtime
      JUPYTER_CONFIG_DIR: /home/jovyan/.rsm-msba/jupyter
      RPASSWORD: rstudio
      JPASSWORD: jupyter
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8787:8787
      - 127.0.0.1:8989:8989
      - 127.0.0.1:8765:8765
    volumes:
      - ~:/home/jovyan
      - pg_data:/var/lib/postgresql/10/main

volumes:
  pg_data:
    external: true
```
