### ISSUE TITLE
Stuck on "Starting server" 

### ISSUE THREAD

**Issue by olaven** [microsoft/vscode-remote-release#3228]
Hi, thanks for this amazing technology!
I hope this is the right repository for this bug report. 
Thanks for maintaining, have a nice day 😄 

## Description
When attempting to connect to remote containers, the program seemingly halts at `Starting with Dev Containers: Starting server`. This error occured today, even though there are not any changes to my project that I am aware of. 

## Configuration files 
```json
{
	"name": "development",
	"dockerComposeFile": "docker-compose.yml",
	"service": "web",
	"workspaceFolder": "/workspace",
	"forwardPorts": [
		3000,
		5432
	],
	"postCreateCommand": "yarn install",
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"extensions": [
		"dbaeumer.vscode-eslint",
		"firefox-devtools.vscode-firefox-debug",
		"github.vscode-pull-request-github"
	]
}
```
```yml
  version: '3'
  services:
    web:
      image: node:12
      volumes:
        - ..:/workspace:cached
      command: sleep infinity
  
      links:
        - db
  
    db:
      image: postgres
      restart: unless-stopped
      ports: 
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: data
```

## Information

- VSCode Version: 1.47.0-insider
- Local OS Version: macOS Catalina 10.15.5 
- Remote OS Version: https://hub.docker.com/_/node/ version 12
- Remote Extension/Connection Type: Docker / Docker Compose

Steps to Reproduce:

1. setup a project with my configuration
2. Run "Remote-Containers: Rebuild and Reopen in Container"

Does this issue occur when you try this locally?: The issue is related to connecting, so I think this does not apply.
Does this issue occur when you try this locally and all extensions are disabled?: Yes (except "Remote-Containers", which has to be enabled. 

__EDIT__:
* Not occuring in stable vscode 
* Not occuring in project with `Dockerfile` (not `docker-compose.yml`)
