### ISSUE TITLE
Shutdown action not executed on vscode close in wsl2 remote environment

### ISSUE THREAD

**Issue by zikhan** [microsoft/vscode-remote-release#3272]
Issue Type: <b>Bug</b>

I'm using devcontainer.json with a docker-compose file in the wsl2 environment.

When closing vs code, the docker-compose services are still running. The expected behavior is that the docker-compose project should either be downed or stopped.

Here is my devcontainer.json
```json
{
    "name": "Rust Proxy",
    "dockerComposeFile": "docker-compose.yml",
    "service": "workspace",
    "workspaceFolder": "/workspace",
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash",
        "lldb.executable": "/usr/bin/lldb"
    },
    "extensions": [
        "rust-lang.rust",
        "bungcip.better-toml",
        "vadimcn.vscode-lldb",
        "ms-azuretools.vscode-docker"
    ],
    "forwardPorts": [ 8080, 8000 ],
    "remoteUser": "vscode",
    "shutdownAction": "stopCompose"
}
```

Here is the docker-compose.yml
```yaml
version: "3.5"

networks:
  crabproxy:
    name: crabproxy

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker-host.sock
    networks:
      - crabproxy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - crabproxy
  dynamodb_bootstrapper:
    image: amazon/aws-cli
    user: 1000:1000
    environment:
      - DYNAMO_FOLDER=/dynamodb
      - REGION=us-west-2
      - ENDPOINT_URL=http://dynamodb:8000
    volumes: 
      - "./DynamoDB:/dynamodb"
    networks:
      - crabproxy
    depends_on:
      - dynamodb
    entrypoint: /dynamodb/loader.sh
```

Docker-compose status with vscode closed: 
![image](https://user-images.githubusercontent.com/8488326/86060669-d7cab400-ba2a-11ea-93c1-d9284d7e04e8.png)

Extension version: 0.122.1
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Rust Proxy|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|24.97GB (20.71GB free)|
|VM|0%|
</details>
