### ISSUE TITLE
Should a devcontainer run --service-ports when it builds the container from docker-compose?

### ISSUE THREAD

**Issue by nathanjwtx** [microsoft/vscode-remote-release#3386]
- VSCode Version: 1.47.2
- Local OS Version: Windows 10 19041.329
- Remote OS Version: Debian
- Remote Extension/Connection Type: Docker/WSL2

Steps to Reproduce:

1. Build a new devcontainer by selecting Open folder in remote container
2. Choose use existing docker-compose file

If I run `docker-compose ls` i can see the ports have been forwarded as specified. However, I am unable to connect to the running container when it run from VS Code. If I stop it, and then run it with regular docker command to start a container I can connect.

I asked on StackOverflow and it was suggested the perhaps `There are certain networking operations that do not occur until up is called. VSCode may be running the container without --service-ports, which is what exposes those port mappings`

My SO post link if that is helpful
https://stackoverflow.com/questions/62764077/how-do-i-make-my-vs-code-dev-remote-container-port-accessible-to-localhost

Here is the docker-compose file and Dockerfile, with some company info removed.

```
FROM docker.removed.local/node
MAINTAINER removed

WORKDIR /opt/app

COPY package.json /opt/app/package.json
COPY package-lock.json /opt/app/package-lock.json
COPY .npmrc /opt/app/.npmrc
RUN echo "nameserver 192.168.11.1" > /etc/resolv.conf && npm ci
RUN mkdir -p /opt/app/logs

# Setup a path for using local npm packages
RUN mkdir -p /opt/node_modules

ENV PATH /opt/node_modules/.bin:$PATH

COPY ./ /opt/app
EXPOSE 80

ENV NODE_PATH /opt:/opt/app:$NODE_PATH
ARG NODE_ENV

VOLUME ["/opt/app"]

CMD ["forever", "-o", "/opt/app/logs/logs.log", "-e", "/opt/app/logs/error.log", "-a", "server.js"]
```

```
version: '3.5'
services:
  server:
      build: .
      container_name: removed-data-graph
      command: nodemon --ignore 'public/*' --legacy-watch src/server.js
      image: docker.removed.local/removed-data-graph:local
      ports:
          - "9999:80"
      volumes:
          - .:/opt/app
          - /opt/app/node_modules/
            #- ${LOCAL_PACKAGE_DIR}:/opt/node_modules
      depends_on:
          - redis
      networks:
          - company-network
      environment:
          - NODE_ENV=dev
  redis:
      container_name: redis
      image: redis
      networks:
          - company-network
      ports:
          - "6379:6379"
networks:
    company-network:
        name: company-network
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No
