### ISSUE TITLE
Allow specifying DNS names in addition to ports that should be forwarded

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#3450]
Feature that allows you to specify DNS names (other than “localhost.*") that resolve to 127.0.0.1 and that are then auto-forwarded.

I searched through existing issues and didn't seem to find one, but please feel free to let me know if I might've missed one.

cc @Chuxel

**Comment by Chuxel** [comment]
//cc: @kieferrm @roblourens @mjbvz - FYI, the specific scenario here is wanting to use SSL certificates locked to a host name, but the host name is set to 127.0.0.1 via a hosts file both remotely and locally (or corp DNS). The request is to be able to have the "click on link" feature to work in the scenario, while now we only consider `localhost`, `127.0.0.1`, and `0.0.0.0` as far as I know.

**Comment by tvvignesh** [comment]
@bamurtaugh @Chuxel I am not sure if this is related, but having ability to forward DNS along with ports would be very helpful. 

For instance, if I use [kubefwd](https://github.com/txn2/kubefwd) in my VM with remote ssh, and it forwards all the cluster urls at `http://my-service:port` in my remote machine which I would like to forward to my host machine at `http://my-service:port` so that I can open it in my browser.

Currently, I don't think it is possible since I can only forward ports. This would be really helpful.

**Comment by Chuxel** [comment]
>  Forward DNS along with ports would be very helpful.

@tvvignesh I'd suggest we pull that out into a separate issue since its local to remote.  This is more remote to local.

I tweaked the subject because we've seen an expansion in where this is needed when it comes to Docker Compose - particularly with Codespaces.

## Example

In terms of a concrete example here, let's take a look at a typical Docker Compose definition.  This is what you'd normally want to be able to do:

```yaml
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
```

If you connect to the `app` container that is created, you then have access to postgres in the `db` container.  The database is available on port `5432` in this case.  However, the following does not work in devcontainer.json:

```json
{
    "forwardPorts": [ "5432" ]
}
```

The same is true for automated forwarding and if you use the forward ports UI.  Why?  Because this port is available at `db:5432` not `localhost:5432`.

Today we have a hack in place in our vscode-dev-containers definitions that uses the same network for all containers. This results in `db` being on localhost as well from the `app` container's point of view.  That said, this is not a typical setup.

Ideally, you'd be able to do the following:

```json
{
    "forwardPorts": [ "db:5432" ]
}
```

This would then need support in the UI as well.  

## Auto-forwarding

Its unclear if we can automatically detect this scenario and auto-forward, but it's also worth noting that these URIs will show up in debug output and the terminal.   So, we would want a declarative way to indicate which domains/IPs should be treaded like they are in the container.  Consider this terminal output:

```
Application running at http://localhost:3000
Database admin running at http://db:1234
```
Clicking on `http://db:1234` should trigger port forwarding and a browser then appears at localhost on the local machine if `db` is configured as a known domain.

Perhaps devcontainer.json could include something like this to make this possible:

```json
{
    	"otherPortsAttributes": {
		"autoForwardDomains": [
			"db",
                       "my.domain.in.etc.hosts",
			"142.134.1.22"
		]
	}
}
```
