### ISSUE TITLE
Missing "workspaceFolder" when using docker-compose results in excessive CPU usage from `rg` processes in container and memory usage from `node` - node eventually gets killed with OOM

### ISSUE THREAD

**Issue by jorupp** [microsoft/vscode-remote-release#369]
Edit: this all seems to be caused by having no `workspaceFolder` set in `devcontainer.json`, which I'm guessing results in the entire container being considered in the workspace.

- VSCode Version: 1.35.0-insider
- Local OS Version: Windows 10.0.17134
- Remote OS Version: Linux e9c5668e122c 4.9.125-linuxkit
- Remote Extension/Connection Type: Docker for Windows 2.0.4.1 (Engine: 19.03.0-beta3).
- Host machine: i7-6700K, 32GB.  Docker for Windows allocated 6 CPU + 8GB.

Steps to Reproduce:

1. Starting from existing ASP.Net Core 2.2 project.
2. Add `.devcontainer/devcontainer.json`
```
{
	"name": "...",
	"extensions": [
		"ms-vscode.csharp"
	],
	"dockerComposeFile": ["docker-compose.yaml"],
	"service": "api",
	"workspaceFolder": "/workspace/api"
}
```
3. Add `.devcontainer/docker-compose.yaml`
```
version: '3.2'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/api

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
     - "5000:80"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 
```
4. Add `devcontainer/Dockerfile`:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2

# Install git, process tools
RUN apt-get update && apt-get -y install git procps

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
```
5. Start workspace.
6. Wait.  (can open a terminal and run `ps` or `top` to watch the numbers spin up)

The RG processes take up a lot of CPU immediately, and the node process gradually increases in memory until it's killed.
Top soon after starting: https://imgur.com/PP3esbt
Top several minutes later: https://imgur.com/HaJnTcB
Eventually, VSCode shows "Attempting to reconnect", and sometimes `docker ps` starts taking a very long time to respond.
Docker eventually kills `node` with OOM:
```
[23:17:38.399][Moby           ][Info   ] [ 6373.283093] Out of memory: Kill process 21660 (node) score 793 or sacrifice child
[23:17:38.409][Moby           ][Info   ] [ 6373.291203] Killed process 21660 (node) total-vm:80992356kB, anon-rss:6949436kB, file-rss:0kB, shmem-rss:0kB
```

Unsure if it's related, but the whole filesystem is showing in the workspace: https://imgur.com/Whcpii3 (ie. `workspaceFolder` doesn't seem to be working).  Could ripgrep be trying to index the entire container instead of just my workspace?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Edit:
Minimal repro available at https://github.com/jorupp/vscode-remote-container-perf, create by taking https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnetcore-2.1 and switching to docker-compose.
