### ISSUE TITLE
workspace not mount into container automatically when use docker-compose

### ISSUE THREAD

**Issue by markshao** [microsoft/vscode-remote-release#4106]
- VSCode Version: 

```yaml
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```
- Remote OS Version:- Remote Extension/Connection Type:  Docker

Steps to Reproduce:

1. .devcontainer/devcontainer.json content 
```json
{
    "dockerComposeFile": "docker-compose.yaml",
    "service": "mercury",
    "workspaceFolder": "."
}
```

2. docker-compose
```yaml
version: "3.8"

services:
  mercury:
    # depends_on:
    #   - mongodb
    #   - zk
    # build:
    #   context: ".."
    #   dockerfile: ".devcontainer/Dockerfile"
    image: mcr.microsoft.com/vscode/devcontainers/go:1.15
    environment:
      CONF_FILE: "config_devbox.yaml"
    command: /bin/sh -c "while sleep 1000; do :; done
```

3. choose reopen in container,  could not found /workspace mount inside container . but if I use image not docker-compose , it woill automatically mount in /workspace
