### ISSUE TITLE
Neither "postStartCommand" nor "postAttachCommand" works opening a dev container

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode-remote-release#4190]
- VSCode Version: 1.52
- Local OS Version: Win10 Pro
- Remote OS Version: Alpine Linux 3.11
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

Given the configuration listed below, I'm trying to enable a situation where I can `docker-compose up -d` a container (or set of containers) and then in VsCode open the dev container for one of the already running containers, and have it automatically attach the tmux session in the console.

However opening VsCode, pressing CTRL+R and from the recent list selecting `node5 [Dev Container]` this does not occur.

It's not clear whether opening a dev container in this manner consititutes attaching to the existing container or starting the dev container, at any rate neither "postStartCommand" nor "postAttachCommand" connect the terminal to the running tmux session, whereas manually running `npm run startx` or `tmux attach -t my_session` does work.

How do I get this to just work automatically?

Dockerfile
```
FROM node:lts-alpine
RUN apk add tmux
```
docker-compose
```
version: "3.8"
services:
  node5:
    build: ./
    user: node
    tty: true
    stdin_open: true
    volumes:
      - ./:/node5
      - /node_modules
    working_dir: /node5
    command: npm run startx
    ports:
      - 3000:3000
```
devcontainer.json
```
{
   "dockerComposeFile": "./docker-compose.yml",
   "service": "node5",
   "workspaceFolder": "/node5",
   "postStartCommand": ["npm", "run", "startx"]
}
```
package.json
```
{
  "name": "node5",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "start": "nodemon server.js",
    "startx": "(tmux new -s my_session 'nodemon server.js' || tmux attach -t my_session)",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  },
  "devDependencies": {
    "nodemon": "^2.0.6"
  }
}
```
