### ISSUE TITLE
Remote-Containers CLI: RPC pipe not configured.

### ISSUE THREAD

**Issue by fhuonder** [microsoft/vscode-remote-release#4202]
- VSCode Version: 1.52
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker/WSL

I have Windows 10 with Docker for Windows, WSL 2 and the docker engine is integrated into the WSL2.
The devcontainer is a Ubuntu 20.04 based image.

In the WSL I configured git according to https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git (git credential manager setup).
In the running devcontainer git works.
In the devcontainer's bash shell it does not. On every git command it says
```Remote-Containers CLI: RPC pipe not configured. Message: {"command":"fill","stdin":"protocol=https\nhost=bitbucket.org\nusername=fhuonder\n"}```

In the devcontainer's bash the git config for the credential helper looks like
```credential.helper=!f() { /root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/node /tmp/vscode-remote-containers-f71604cb655ae555002aed74e1d2d934ff7f5afe.js $*; }; f```

Any hints?
I already searched to issues but only found similar issue but not exactly the same.

Regards,
Florian

**Comment by chrmarti** [comment]
Is the `REMOTE_CONTAINERS_IPC` environment variable somehow unset in your terminal?

**Comment by fhuonder** [comment]
Hi @chrmarti 
It is set
```
root@2da8b293a15f:/workspaces/myworkspace# echo $REMOTE_CONTAINERS_IPC
/tmp/vscode-remote-containers-ipc-5dc5cb2dc65472fbedc40278f4bd1686999cf2c9.sock
```

**Comment by chrmarti** [comment]
The error message should only show when that environment variable is not set. Could you post your devcontainer.json?

**Comment by fhuonder** [comment]
Here it is
```
{
	"name": "digitalassitant-app",
	"dockerComposeFile": [
		"./docker-compose.yml"
	],
	"service": "digitalassistant-app",
	"shutdownAction": "stopCompose",
	"workspaceFolder": "/workspaces/myworkspace",
	"extensions": [
		"ms-azuretools.vscode-docker@1.8.1",
		"dart-code.dart-code@3.17.0",
		"dart-code.flutter@3.17.0",
		"k--kato.intellij-idea-keybindings@0.2.41",
		"abhiagr.logcat@0.0.7",
		"humao.rest-client@0.24.4"
	],
	"forwardPorts": [
		9100
	],
	"remoteEnv": {
		"ANDROID_SDK_ROOT": "/android-sdk",
		"ANDROID_HOME": "/android-sdk"
	},
	"settings": {
		"workbench.editor.enablePreview": false,
		"workbench.editor.enablePreviewFromQuickOpen": false,
		"files.associations": {
			"*.arb": "json"
		},
		"debug.openDebug": "openOnDebugBreak",
		"dart.flutterSdkPath": "/flutter",
		"dart.lineLength": 180,
		"editor.rulers": [
			180
		],
		"[dart]": {
			"editor.selectionHighlight": false,
			"editor.suggest.snippetsPreventQuickSuggestions": false,
			"editor.suggestSelection": "first",
			"editor.tabCompletion": "onlySnippets",
			"editor.wordBasedSuggestions": false,
		}
	},
	"postStartCommand": "flutter doctor -v"
}
```

**Comment by chrmarti** [comment]
Could you also attach the docker-compose.yml? I'd like to understand if there is a chance of the credential helper being called twice.

**Comment by fhuonder** [comment]
```
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
          - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
          - TZ=Europe/Zurich
        volumes: 
          - ..:/workspaces/myworkspace:delegated
          - ~/.aws:/home/root/.aws:ro
          - app-commandhistory:/commandhistory
          - app-androidsdk:/android-sdk
          - app-pubcache:/flutter/.pub-cache
          - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - app-network
        command: >
            bash -c "
            { echo -n 10388 | xargs -d ' ' -I% bash -c 'socat tcp-listen:%,fork tcp:host.docker.internal:% &' ; }
            && /bin/sh -c \"while sleep 1000; do :; done\""

networks:
    app-network:
        external:
            name: xyz

volumes:
    app-commandhistory:
    app-androidsdk:
    app-pubcache:

```
