### ISSUE TITLE
Specify docker network(s) in devcontainer.json

### ISSUE THREAD

**Issue by slmg** [microsoft/vscode-remote-release#4272]
I regularly work on distributed components communicating via their own network.
All it takes is to run `docker network create app-network` once and then add the below to every docker-compose.yaml.

```yaml
# override the default network
networks:
  default:
    external:
      name: app-network
```

As I am using this great extension to develop directly into my apps' environment, I would find the ability to specify additional networks to attach to the devcontainer a very useful feature. This would enable users to leverage docker-compose host names resolution.

As an example, if I had the below running in my network:

```yaml
version: "3.7"

services:
  app-db:
    image: postgres
    # ...

networks:
  default:
    external:
      name: app-network
```

and if I could pass `app-network` to devcontainer.json, I would be able to connect to my db using a connection string like `postgresql://user:password@app-db:5432/somedb` inside my dev container. In addition to being nice to pass host names vs ip, this would allow me to connect without at any point exposing this db to my entire network (which is what I am forced to do at the moment).

I know that devcontainer.json can use docker-compose directly, but I think it would make sense to include this in devcontainer.json, so as to not require any user wishing to operate in a different network than the host one, a complete devcontainer refactor.

Thank you.
