### ISSUE TITLE
Environment variables are not reflected only when Open Folder in Container is used.

### ISSUE THREAD

**Issue by milmed13** [microsoft/vscode-remote-release#4332]
I open the `server` directory from `Remote Containers: Open Folder in Container`, the environment variables are not reflected in the dockerfile.

If you run `docker-compose up -d` from `root`, the variable TEST will be reflected as true.

I could not do it by specifying `.env` from `env_file` in docker-compose.

How can I get the variable TEST to output true set in `.env`?

#### run environment

```
OS: Windows10
  WSL2 Ubuntu 20.04.1
docker: 20.10.0
```

#### project tree

```
root
|- .devcontainer
|   |- docker-compose.yml
|- docker
|    |- Dockerfile
|- client (src)
|- server (src)
|   |- .devcontainer.json
|- .env
|- docker-compose.yml 
```

#### /dcoer-compose.yml

```
version: "3"

services:
  php:
    build:
      context: ./docker/php
      args:
        - TEST=${TEST}
    env_file:
      - .env
```

#### /.env

```
TEST=true
```

#### /docker/Dockerfile

```
FROM php:7.4-fpm

ARG TEST

# ${TEST} is empty

```

#### /server/.devcontainer.json

```
{
	"name": "php",
	"dockerComposeFile": [
		"../docker-compose.yml",
		"../.devcontainer/docker-compose.yml"
	],
	"service": "php",
	"workspaceFolder": "/workspace/server",
	"shutdownAction": "none",
	"settings": {
	},
	"extensions": [
	]
}
```
