### ISSUE TITLE
Cannot start devcontainer with vscode extensions volumes

### ISSUE THREAD

**Issue by fatindeed** [microsoft/vscode-remote-release#4355]
- VSCode Version: 1.52.1
- Local OS Version: macOS Catalina 10.15.7
- Name of Dev Container Definition with Issue: go:latest

Steps to Reproduce:

1. docker-compose.yml for devcontainer according to [Avoiding extension reinstalls on container rebuild](https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild)
```yaml
version: '3.4'
services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/go
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace
      - vscode_extensions:/home/vscode/.vscode-server/extensions
    command: ["sleep", "infinity"]
volumes:
  vscode_extensions:
```
2. error log
```
...
[3521 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[3527 ms] 
[3527 ms] mkdir: cannot create directory '/home/vscode/.vscode-server/data': Permission denied
[3527 ms] Exit code 1
[3527 ms] Start: Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[3530 ms] 
[3530 ms] cat: /home/vscode/.vscode-server/data/Machine/settings.json: No such file or directory
[3530 ms] Exit code 1
[3530 ms] Start: Run in container: test -d /home/vscode/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523
[3532 ms] 
[3532 ms] 
[3532 ms] Exit code 1
[3533 ms] Installing VS Code Server for commit ea3859d4ba2f3e577a159bc91e3074c5d85c0523
[3533 ms] Start: Run in container: mkdir -p /home/vscode/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523_1611537557933
[3536 ms] 
[3537 ms] mkdir: cannot create directory '/home/vscode/.vscode-server/bin': Permission denied
[3537 ms] Exit code 1
[3540 ms] Command in container failed: mkdir -p /home/vscode/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523_1611537557933
```

### Sugguestion

It would be better if you create `.vscode-server` and `.vscode-server-insiders` within Dockerfile, this issue will be fixed
```
mkdir -p /home/vscode/.vscode-server /home/vscode/.vscode-server-insiders \
chown -R vscode:vscode /home/vscode/.vscode-server* \
```
