### ISSUE TITLE
Test: Remote-Containers SSH password entry

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4362]
Refs: #4154

- [x] Windows @meganrogge
- [x] AnyOS @weinand

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%234362%0A%0A)

---

This first explains how to setup an SSH server running a Docker daemon (using containers). This can be skipped if an SSH server with a Docker daemon is available. It requires Docker Desktop (Docker and Docker Compose CLIs).

Create a folder with the following two files (also in the private repo: https://github.com/microsoft/vscode-remote-containers/tree/master/test-remotes/ssh-password):

`docker-compose.yml`:
```
version: "3.7"
services:

  dockerd:
    image: docker:dind
    privileged: true
    network_mode: bridge
    ports:
      - "127.0.0.1:23750:2375"
    command: "dockerd --host=tcp://0.0.0.0:2375"

  sshd-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    network_mode: bridge
    links:
      - dockerd
    ports:
      - "127.0.0.1:2223:22"
    depends_on:
      - dockerd
```

`Dockerfile.ubuntu`:
```
FROM rastasheep/ubuntu-sshd:18.04

RUN apt-get update && apt-get install -y docker.io

RUN echo PermitUserEnvironment yes >>/etc/ssh/sshd_config
RUN mkdir -p /root/.ssh
RUN echo DOCKER_HOST=tcp://dockerd:2375 >>/root/.ssh/environment
```

Start from this local folder with:
```
docker-compose up -d --build
```

- Install the Remote-Containers and Remote-SSH extensions.
- `F1` > `Remote-SSH: Connect to Host...`
  - `root@localhost:2223`
  - Passwort is `root`.
- Open folder (e.g., `/root`) in Remote-SSH to work around https://github.com/microsoft/vscode/issues/111371.
- In the following make sure:
  - You are asked for the password only once per window.
  - You are not asked for the password without having taken an action that requires it.
  - Everything else works as usual.
    - Reopening a folder from a Remote-SSH session with Remote-Containers is not yet supported.
    - Opening a repository in a volume doesn't work in this setup.
- Open Remote Explorer and switch to Containers.
- Start a few containers with `docker run -d alpine sleep infinity` for testing.
- Attach to these containers.
  - From the Remote Explorer.
  - Using `F1` > `Remote-Containers: Attach to Running Container...`.

Cleanup from this local folder with:
```sh
docker-compose down
```
