### ISSUE TITLE
Docker start event never get fired when used in combination of docker compose

### ISSUE THREAD

**Issue by cgmon** [microsoft/vscode-remote-release#4449]
- VSCode Version: 1.53.0
- Local OS Version: Windoes 10 Pro 10.0.19041
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create a devcontainer project with the following docker-compose.yml
```yml
services:
    myservice:
    image: "mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14"
    volumes:
     - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
```
2. Reopen folder in container
3. It hangs at `docker events --format {{json .}} --filter event=start`
```log
[89474 ms] Start: Run: docker events --format {{json .}} --filter event=start
[97661 ms] Start: Run: docker-compose --project-name remote -f c:\Users\dmonras\test\docker-compose.yml up -d
Recreating remote_myservice_1    ... done
[105778 ms] Stop (8117 ms): Run: docker-compose --project-name remote -f c:\Users\dmonras\test\docker-compose.yml up -d

```
4. The container is running as far as I can see in my docker desktop GUI. In fact, if I restart the container the docker start event is triggered and the process goes back on.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes
