### ISSUE TITLE
Rebuild with Compose fails

### ISSUE THREAD

**Issue by tuky** [microsoft/vscode-remote-release#4621]
- VSCode Version:
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:50.094Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-44-generic
- Remote OS Version: Ubuntu 20.4 (Linux truffls 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
- Remote Extension/Connection Type: Docker with compose

Steps to Reproduce:

`devcontainer.json`:

```json
{
	"name": "Development Container",

	"dockerComposeFile": [
		"../docker-compose.yml",
		"docker-compose.yml"
	],
	"service": "server",
	"workspaceFolder": "/code",
	"settings": {
		"terminal.integrated.shell.linux": "/usr/bin/bash",
		"files.watcherExclude": {
			"**/.git/objects/**": true,
			"**/.git/subtree-cache/**": true,
			"**/src/media/**": true
		}
	},
	"extensions": [
		"ms-azuretools.vscode-docker",
		"ms-python.python",
		"ms-python.vscode-pylance",
		"ms-toolsai.jupyter",
		"batisteo.vscode-django",
		"mrorz.language-gettext"
	],
	"runServices": ["server"],
	"shutdownAction": "none",
}
```

`.devcontainer/docker-compose.yml`:

```yml
version: '3.4'
services:
  server:
    build:
      target: development
    ports:
      # django webserver
      - "8080:8080"

    user: "${CONTAINER_UID:?please always set CONTAINER_UID when running with docker compose, e.g. put 'export CONTAINER_UID=\"$(id -u)\"' in your .bashrc }"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/code/
      - ./.docker_home:/home/servant  # to e.g. cache shell history

      # Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```
`CONTAINER_UID` is set to `1000` via `.env` and as environment variable (my personal host user uid). This is working nicely, all files are written as the host user and also github credential helper is working.

See what happens in the screenshot when asking to rebuild the container. The `docker rm -f <container_id>` command fails and the rebuild stops:
![image](https://user-images.githubusercontent.com/2981274/110322242-1e899880-8013-11eb-918e-3d1ead40c08c.png)
Thanks for your help in resolving this!
