### ISSUE TITLE
Expose uniqueVolumeName as an environment variable to docker-compose when instantiating the devcontainer

### ISSUE THREAD

**Issue by k8n** [microsoft/vscode-remote-release#4660]
When cloning a repository into a volume (or a unique volume),
it would be great if the `uniqueVolumeName` (which is exposed as the `vsch.local.repository.volume` label via docker-`compose.repositoryContainer.yml` created in the bootstrap process) is exposed to the environment. (And not set when no code-in-volume is involved.)

That would permit to easily connect multiple containers to the workspace to separate concerns (e.g. a container to serve and a container to develop and build).

*docker-compose.yml*
```
version: "3"

services:
  dev:
    ...
    volumes:
      # code bootstrapped into this volume by the extension
      - ${uniqueVolumeName}:/workspaces

  fancy_nginx:
    ...
    volumes:
      - ${uniqueVolumeName}:/var/www
```

Please? It's a one-liner, I'm certain.
