### ISSUE TITLE
Forward ports for other hosts in docker compose file

### ISSUE THREAD

**Issue by rvanlaar** [microsoft/vscode-remote-release#5578]
I would love if `forwardPorts` in devcontainer.json can allow for other hosts, i.e.: `forwardPorts: ["mailhog:8025"]
The solution for now is to put every container in the same network: https://github.com/microsoft/vscode-remote-release/issues/5319

We use docker-compose to spin up multiple services. One of them is mailhog. See this docker-compose file as an example?
```
version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        # [Choice] Install Node.js
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        # USER_UID: 1000
        # USER_GID: 1000

    volumes:
      - /root/workbench:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
```
