### ISSUE TITLE
Clone repository in Container Volume - Ensure volume is mounted to all docker-compose services that refer to it

### ISSUE THREAD

**Issue by mpriscella** [microsoft/vscode-remote-release#5587]
When using the `Remote-Containers: Clone Repository in Container Volume` with a repository that mounts the same directory into two services using a `docker-compose.yml` file, the volume mount information is only added to the service defined by `"service"` in `devcontainer.json`.

For example, if I have the following `docker-compose.yml` file:
```
version: '3.7'

services:
  php:
    image: php:7.4
    volumes:
      - ../:/var/www/html

  nginx:
    image: nginx:1.19
    volumes:
      - ../:/var/www/html
```

And I am connecting to the `php` service using VSCode, the resulting `docker-compose.yml` file will be something like:
```
version: '3.7'

services:
  php:
    image: php:7.4
    volumes:
      - ../:/var/www/html
      - repo-branch-hash:/workspace

  nginx:
    image: nginx:1.19
    volumes:
      - ../:/var/www/html

volumes:
  repo-branch-hash:
    external: true
    name: repo-branch-hash
```

Ideally, the extension would look for any defined mount to `../` and make sure the volume is mounted to that service.
