### ISSUE TITLE
Use interactive login shell to probe WSL env vars

### ISSUE THREAD

**Issue by nbraun-wolf** [microsoft/vscode-remote-release#5806]
- VSCode Version: 1.61.2
- Local OS Version: wsl2 ubuntu 20.04
- Reproduces in:| Remote - Containers | 
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

HI, I have some variables set in my shell from my bashrc. I am unable to pass them to the devcontainer started from a compose file. It works with regular compose up, as its feature of compose to pick env variables either from shell or a .env file next to the first compose file that is used. 

```yaml
services:
  environment:
    PIP_EXTRA_INDEX_URL:
   # other variables loaded from .env file
```      

Doing it from the devcontainer.json as documented also doesnt work.

```json
  "remoteEnv": {
    "PIP_EXTRA_INDEX_URL": "${localEnv:PIP_EXTRA_INDEX_URL}",
  },
```

I really don't want to write this in a .env file within the repository, since it's confidential and shouldn't get source controlled. I want to use it as it's set in the shell through my bashrc.
