### ISSUE TITLE
Docker compose volume source resolves to `/root` for `~` and `$HOME`

### ISSUE THREAD

**Issue by eddiecorrigall** [microsoft/vscode-remote-release#5920]
- VSCode Version: 1.62.2 (Universal)
- Devcontainer Extension Version: v0.205.2
- Local OS Version: macOS Big Sur 11.5.2
- Remote OS Version: `mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14`
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:

```
Starting code_devcontainer_pubsub_1 ... error

ERROR: for code_devcontainer_pubsub_1  Cannot start service pubsub: Mounts denied: 
The path /root/.config/gcloud is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

ERROR: for pubsub  Cannot start service pubsub: Mounts denied: 
The path /root/.config/gcloud is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
```

**Steps to Reproduce:**

1. Assign a volume to a service in a devcontainer docker-compose.yaml with a source containing `~` or `$HOME`
2. Open VS Code command pallet and run "Remote-Containers: Clone Repository into Container Volume..."

**docker-compose.yaml:**

```
...
  pubsub:
    image: google/cloud-sdk:311.0.0
    entrypoint:
      - bash
      - -c
      - |
        gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    volumes:
      - ${HOME}/.config/gcloud:/root/.config/gcloud
    ports:
      - '8085:8085'
    environment:
      - GCLOUD_PROJECT=<removed>
    networks:
      - <removed>
```

**Output from VS Code Remote - Containers Extension:**

```
  pubsub:
    entrypoint:
    - bash
    - -c
    - 'gcloud beta emulators pubsub start --host-port=0.0.0.0:8085

      '
    environment:
      GCLOUD_PROJECT: <removed>
    image: google/cloud-sdk:311.0.0
    networks:
      <removed>: {}
    ports:
    - published: 8085
      target: 8085
    volumes:
    - /root/.config/gcloud:/root/.config/gcloud:rw
```

Expected `- /Users/<username>/.config/gcloud:/root/.config/gcloud:rw`

**Fixes:**

- Downgrade VS Code extension Remote - Containers to version v0.200.0 to use "Remote-Containers: Clone Repository into Container Volume..."
- Use Command Pallet "Remote-Containers: Open Folder in Container..." with version v0.200.0 or v0.205.2
