### ISSUE TITLE
Problems with FileSystem (missing files) when additional volume mounts used

### ISSUE THREAD

**Issue by wclr** [microsoft/vscode-remote-release#6007]
- VSCode Version:
- 1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64

- Local OS Version: Microsoft Windows [Version 10.0.19043.1348]
- Remote OS Version: Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: Docker
- Docker for Windows 4.2.0 (70708): Engine: 20.10.10

**NB!** With the latest insiders, the problem even seems worse at glance - it even doesn't work without additional mounts.

Steps to Reproduce:

This bug I have on a particular project so made a repo available which needed to be cloned (particular branch) and opened in the container.

https://github.com/wclr/purescript/tree/vscode-remote-fs-issue
- Clone and run in the container
- Check files in src (in my case there a lot of issues with missing files)
![image](https://user-images.githubusercontent.com/736697/144911058-a4f45ded-cdb4-4745-8b31-54dcc258ad63.png)

- May run `stack build` command to see if it can build.

dockercontainer config:
```js
  "workspaceFolder": "/purescript",
  
  "workspaceMount": "source=${localWorkspaceFolder},target=/purescript,type=bind",  
```
It seems to work ok (no missing/bad files) if no additional mounts are specified.

If to specify additional volume mounts that are needed for the build to work:
```js
  "mounts": [    
    "type=volume,target=/purescript/output",
    "type=volume,target=/purescript/.stack-work",
    "type=volume,target=/purescript/.test_modules",
    "type=volume,target=/purescript/.psci_modules",
    "type=volume,target=/purescript/lib/purescript-cst/.stack-work"
  ]
```
then we have those problems with missing or nonopening files:
![image](https://user-images.githubusercontent.com/736697/144909375-8d50c080-9aa3-43e3-8dec-a88ee0a6a8d7.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@wclr The `"mounts"` you list do not include a volume name (as `source`) so they create new volumes each time you rebuild the container. Does that explain the missing files?

**Comment by wclr** [comment]
> The "mounts" you list do not include a volume name (as source) so they create new volumes each time you rebuild the container. Does that explain the missing files?

No, it is about missing files that should come from the host, they are not inside those additionally mounted volumes. I'm quite familiar with how the docker volume mounts work. 

So I actually tried with just a `docker compose` without involving vscode remote:
```yaml
version: '3.0'
volumes:  
  stack-work: null
  lib_purescript-cst_stack-work: null

services:
  purescript:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    command: /bin/sh
    working_dir: '/purescript'
    volumes:
      - './:/purescript'
      - 'stack-work:/purescript/.stack-work'
      - 'lib_purescript-cst_stack-work:/purescript/lib/purescript-cst/.stack-work'
```

And it seems the problem of docker with WSL2 (https://github.com/docker/for-win/issues/7552) is that it has problems with file mapping files from the host. 

I believe you just can see those issues if you clone the repo and run in the container, then examine `src` dir or run `stack build` which should fail with some Input/output error (that it can not read dir/file that should actually be there).
