### ISSUE TITLE
Environment variables are not fully available in devcontainer

### ISSUE THREAD

**Issue by miaoz2001** [microsoft/vscode-remote-release#6439]
Issue Type: <b>Bug</b>

I have set up the devcontiner dev environment, it works perfectly as expected, thanks for the great work!
There is just one thing I couldn't figure it out, not sure it is a bug or something I made wrong.

It's about the environment variables, so I have those env_vars in my bash WSL2 and I also put an envfile in .devcontainer folder, as below in my .devcontainer/docker-compose.yml file
```
    env_file: .devcontainer/devcontainer.env
```
I suppose when I start the devcontainer, all my env_vars should be available in my shell of devcontainer, but only some of them are there! not None, not all, but some of them! It's really strange.

my devcontainer.json
```
{
  "name": "django-xxx",

  "dockerComposeFile": [
    "../docker-compose.yml",
    "../docker-compose-local.yml",
    "docker-compose.yml"
  ],

  "service": "backend",

  "workspaceFolder": "/workspace",

  // Set *default* container specific settings.json values on container create.
  "settings": {},

  // Add the IDs of extensions you want installed when the container is created.
  "extensions": [
    "EditorConfig.EditorConfig",
    "HookyQR.beautify",
    "batisteo.vscode-django",
    "donjayamanne.githistory",
    "ms-toolsai.jupyter",
    "ms-python.python",
  ],
```

my docker-compose.yml in .devcontainer folder
```
version: '3'
services:
  backend:
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock


    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - .devcontainer/devcontainer.env

``` 

my original docker-compose files in project folder
```
version: "3"

services:
  backend:
    image: django-XXXX
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS
      - DJANGO_SECRET_KEY
      - DJANGO_SETTINGS_MODULE
      - CACHE_BACKEND
      - CACHE_LOCATION
      - DEFAULT_FILE_STORAGE
      - DD_AGENT_HOST
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DATADOG_TRACE_ENABLED=true
     ....
```

And the log is 
```
[4113 ms] services:
  backend:
    build:
...
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
    - database
    - redis
    environment:
      ALLOWED_HOSTS: null
      CACHE_BACKEND: null
      CACHE_LOCATION: null
      DATADOG_TRACE_ENABLED: "true"
      DD_AGENT_HOST: null
      DD_ENV: null
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_LOGS_INJECTION: "false"
      DD_LOG_LEVEL: critical
      DD_SERVICE_MAPPING: null
      DD_SERVICE_NAME: null
...


```

I noticed that only the envs having values are available in the shell like `DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL`,  `DATADOG_TRACE_ENABLED`, etc. all others are `null` are NOT available in container's shell. But all those envs are in my WSL2 shell when I start devcontainer **(I guess they are not taking when start devcontainer somehow....)**

AND also env_file in docker-compose does NOT have any effects.

If I have to guess, I think when devcontainer starts it didn't take env_vars from the shell, is this a bug or by design? or is there a workaround?

Thanks!

---

Extension version: 0.224.2
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.91GB free)|
|Process Argv|--disable-features=CalculateNativeWinOcclusion --crash-reporter-id 47d8d639-de3e-449c-b652-748dde3ee1d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: django-xxx|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.27GB (5.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvsnew555:30450902
vscscmwlcmc:30438804
vscgsvid2:30447481
cppdebugcf:30451567
dockersurvey3:30446832
pynewfile477cf:30450039

```

</details>
