### ISSUE TITLE
Docker-compose environment variable expansion when cloning in named volume is evaluated in container instead of host

### ISSUE THREAD

**Issue by ledouxpl** [microsoft/vscode-remote-release#6540]
Variable expansion in `docker-compose` files seems to occur in the container's context instead of the host. I originally reported this in issue #6250 and confirmed it was fixed. It somehow got broken again in the March release.

One thing to note is that is works fine when the sources are on the host file system. The issue only arises when attempting to use the `Remote Containers: Clone Repository in Container Volume` or `Remote Containers: Clone Repository in Named Container Volume` commands.

VSCodeVersion: 1.66.0
Local OS Version: MacOS Monterey 12.2.1
Remote OS Version: Alpine 3.15
Remote Extension/Connection Type: SSH/Docker/WSL

Docker-compose.yml:
```yaml
version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ${HOME}${USERPROFILE}/.config/gcloud:/root/.config/gcloud:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
```

Logs:
```log
ERROR: for app  Cannot start service app: Mounts denied: 
The path /root/.config/gcloud is not shared from the host and is not known to Docker.
```

Steps to Reproduce:

1. From vscode, run the `Remote Containers: Clone Repository in Named Container Volume` command 
2. Clone my public repro repository: https://github.com/ledouxpl/vsrepro
3. Type in a new docker volume name

As you will see the `${HOME}` environment variable gets resolved to `/root` instead of your local home folder.
