### ISSUE TITLE
An error ocurred setting up the container

### ISSUE THREAD

**Issue by IgnisDa** [microsoft/vscode-remote-release#6787]
- VSCode Version: I have checked with both latest stable (`1.67.2 c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5`) and insider edition (`1.68.0-insider 2260d7cca34384a2838c728850afdd38113ddb47`)
- Local OS Version: Arch Linux 5.18.1-arch1-1
- Remote OS Version: `FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16`
- Remote Extension: Containers
- Logs: 

![image](https://user-images.githubusercontent.com/60938164/172051937-1e62a39f-32ea-4f7c-afef-d8d374ad4e90.png)

I also tested the same with the latest pre-release version but got the same error.

I have another project which does not have a `docker-compose.yml` in `.devcontainer` and that project works fine with the current extension. So I think something is wrong with how the `docker-compose` is used. Here is it for reference.

`.devcontainer/docker-compose.yml`

```yml
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  cache:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-cache:/data

volumes:
  postgres-data:
  redis-cache:
```

`.devcontainer/Dockerfile`

```Dockerfile
ARG VARIANT=16
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

RUN su node -c "npm install -g yarn pnpm @nestjs/cli ts-node @nrwl/cli nx"

# install the esteem cli to make it easier to manage nx monorepos
RUN curl https://raw.githubusercontent.com/IgnisDa/developrs/main/packages/esteem/install.sh | sudo sh -s -- --yes
```

`docker-compose version`

![image](https://user-images.githubusercontent.com/60938164/172052112-26d7e690-c840-4c23-9353-e8c3ad7e7c6a.png)
