### ISSUE TITLE
Version increment causes rebuilt containers from prior version to fail

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [microsoft/vscode-remote-release#6815]
- VSCode Version: 1.67.2
- Local OS Version: Mac OS 10.15.7

Steps to Reproduce:

1. Create a dev container using a previous version of the developer container extension
2. Update the developer container extension to a new version
3. Attempt to rebuild the container
4. Container rebuild will fail with error (in this example, current extension is 0.239.0): 
`Error: ENOENT: no such file or directory, open '.../.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/Dockerfile'`

This is likely not relevant to codespaces.

**Comment by donaldlaforce** [comment]
I can confirm this is happening on Linux as well. "Remote-Containers 0.238.2 in VS Code 1.68.0"

It appears what is happening is the docker-compose.yml context is now relative to the remote-containers extension directory instead of the current project.

The project .devcontainer/docker-compose.yml is defined as

```
version: "3.8"
services:
  app:
    privileged: true
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      privileged: true
    init: true
```

The following Dockerfile ends up trying to be built: `~/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/.devcontainer/Dockerfile`

This results in the same `ENOENT: no such file or directory` error
