### ISSUE TITLE
`Rebuild Container` does not rebuild all containers specified by docker-compose.yaml. 

### ISSUE THREAD

**Issue by tbistr** [microsoft/vscode-remote-release#7131]
# problem

Situation: Using docker-compose for devcontainer, and execute `Rebuild Container`.
- Expected: All container (services) are stopped and removed (like `docker compose down`), then rebuild all containers.
- Actual: Only one container (specified in `devcontainer.json`) is stopped and removed. But other containers (dev-db in my situation) are not stopped. Then, data in containers does not removed.

Is this expected behavior?
I used this to make testing enviroment.
So, data persistence is not desirable.
And in general, if we want to persist data, should use docker volumes.

# solution?

Add option like `shutdownAction`.
(ex. `"rebuildAction": "all"` )
Or, force `docker compose down` before `Rebuild Container`.

# envs

- VSCode Version: 1.70.2
- Local OS Version: Windows 11 Pro 21H2
- Remote OS Version: Ubuntu 20.04.4 LTS on Windows 10 x86_64
- Remote Extension/Connection Type: Containers
- Logs: 

Steps to Reproduce:

1. Build and reopen in container with following settings.
2. Do `Rebuild Container` command.

# settings

devcontainer.json
```json
{
    "name": "Go",
    "dockerComposeFile": "docker-compose.yaml",
    "service": "dev-go",
    "workspaceFolder": "/workspace",
    "extensions": [
        "golang.Go"
    ],
    "remoteUser": "vscode"
}
```

docker-compose.yaml
```yaml
version: "3.8"
services:
  dev-go:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
    ports:
      - 3000:3000
    depends_on:
      - dev-db

  dev-db:
    image: mysql:8.0
    env_file: .env
    environment:
      - LANG=ja_JP.UTF-8
    tty: true

networks:
  default:
```
