### ISSUE TITLE
Can't access service at 0.0.0.0:8000 but I can at localhost:8000 with an additional port forward rule

### ISSUE THREAD

**Issue by CelestialGuru** [microsoft/vscode-remote-release#7137]
# Problem
Instructions for https://code.visualstudio.com/docs/remote/containers#_publishing-a-port unclear/don't work.

If I start my server in the container with `python manage.py runserver` and go to localhost:8000, I get no response. Checking the "Ports" tab in VSCode I have
| Port  | Local Address  | Running Process           | Origin               |
| ----- | -------------- | ------------------------- | -------------------- |
| 39363 | localhost:8000 | Code Extension Host (277) | Auto Forwarded       |
| 8000  | 0.0.0.0:8000   |                           | Statically Forwarded |

If I "Add Port" and just type in 8000, (with the server still running in the terminal tab), I get:

| Port  | Local Address  | Running Process                                  | Origin               |
| ----- | -------------- | ------------------------------------------------ | -------------------- |
| 8000  | localhost:8000 | /usr/local/bin/python manage.py runserver (5421) | User Forwarded       |
| 39363 | localhost:8000 | Code Extension Host (277)                        | Auto Forwarded       |
| 8000  | 0.0.0.0:8000   |                                                  | Statically Forwarded |

I am able to go to localhost:8000 in my browser and access my web server.

Clearly there is a difference between 0.0.0.0:8000 and localhost:8000 in the "Local Address" column.

Nothing fancy in my "hosts" file. No firewall issues that I am aware of.

Why is VSCode dev containers trying to forward to 0.0.0.0:8000 and not localhost:8000?

# Files/config
## devcontainer.json
```json
{
	"name": "TheProject",
	"dockerComposeFile": [
		"../docker-compose.yml",
		"../docker-compose.override.yml",
		"docker-compose.yml"
	],
	"remoteUser": "vscode",
	"service": "django",
	"workspaceFolder": "/app"
}
```

## docker-compose
I'll show you the combined files with `docker compose -f .\docker-compose.yml -f .\docker-compose.override.yml -f .\.devcontainer\docker-compose.yml config`:
```yml
name: project
services:
  django:
    build:
      context: C:\Users\User\project\api
      dockerfile: compose/local/django/Dockerfile
      args:
        DJANGO_ENV: development
    command:
    - /bin/sh
    - -c
    - while sleep 1000; do :; done
    depends_on:
      postgres:
        condition: service_started
    entrypoint:
    - /bin/sh
    - -c
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8000
      published: "8000"
      protocol: tcp
    restart: "no"
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      source: C:\Users\User\project\api
      target: /app
      bind:
        create_host_path: true
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
  postgres:
    image: postgres
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: "5436"
      protocol: tcp
    volumes:
    - type: bind
      source: C:\Users\User\project\api\compose\local\postgresql\docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\User\project\api\compose\local\postgresql\dump-database.sh
      target: /dump-database.sh
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: postgres_volume
      target: /var/lib/postgresql/data
      volume: {}
networks:
  default:
    name: project_default
volumes:
  postgres_volume:
    name: project_postgres_volume
```
