### ISSUE TITLE
docker container shuts down because of pid file

### ISSUE THREAD

**Issue by selim-seyhanoglu** [microsoft/vscode-remote-release#7359]
- VSCode Version: 1.72.1
- Dev Containers Version: v0.255.3
- Local OS Version: Windows Version 10.0.22000 Build 22000
- Remote OS Version: WSL Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: WSL/Containers
- Logs:
Logs inside the airflow worker container. 

What is happening here: First I freshly rebuilt the devcontainer and no problem occurs, then  closed the devcontainer, then reopened it again and that is when I get the error inside the airflow worker container (`ERROR: Pidfile (/opt/airflow/airflow-worker.pid) already exists.
Seems we're already running? (pid: 7)`)

```
[2022-10-13 13:51:36 +0000] [33] [INFO] Starting gunicorn 20.1.0
[2022-10-13 13:51:36 +0000] [33] [INFO] Listening at: http://0.0.0.0:8793 (33)
[2022-10-13 13:51:36 +0000] [33] [INFO] Using worker: sync
[2022-10-13 13:51:36 +0000] [34] [INFO] Booting worker with pid: 34
[2022-10-13 13:51:36 +0000] [35] [INFO] Booting worker with pid: 35
[2022-10-13 13:51:39,155: INFO/MainProcess] Connected to redis://airflow_redis:6379/0
[2022-10-13 13:51:39,166: INFO/MainProcess] mingle: searching for neighbors
[2022-10-13 13:51:40,199: INFO/MainProcess] mingle: all alone
[2022-10-13 13:51:40,219: INFO/MainProcess] celery@57982842b5a2 ready.
[2022-10-13 13:54:31 +0000] [34] [INFO] Worker exiting (pid: 34)
[2022-10-13 13:54:31 +0000] [35] [INFO] Worker exiting (pid: 35)

worker: Warm shutdown (MainProcess)
[2022-10-13 13:54:31 +0000] [33] [INFO] Handling signal: term

BACKEND=redis
DB_HOST=airflow_redis
DB_PORT=6379

 
 -------------- celery@57982842b5a2 v5.2.0 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5 2022-10-13 13:51:37
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         airflow.executors.celery_executor:0x7f2678761eb0
- ** ---------- .> transport:   redis://airflow_redis:6379/0
- ** ---------- .> results:     postgresql://airflow:**@airflow_postgres/airflow
- *** --- * --- .> concurrency: 16 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> default          exchange=default(direct) key=default
                

[tasks]
  . airflow.executors.celery_executor.execute_command


BACKEND=redis
DB_HOST=airflow_redis
DB_PORT=6379

[2022-10-13 13:56:11 +0000] [24] [INFO] Starting gunicorn 20.1.0
[2022-10-13 13:56:11 +0000] [24] [INFO] Listening at: http://0.0.0.0:8793 (24)
[2022-10-13 13:56:11 +0000] [24] [INFO] Using worker: sync
[2022-10-13 13:56:11 +0000] [25] [INFO] Booting worker with pid: 25
[2022-10-13 13:56:11 +0000] [26] [INFO] Booting worker with pid: 26
ERROR: Pidfile (/opt/airflow/airflow-worker.pid) already exists.
Seems we're already running? (pid: 7)
[2022-10-13 13:56:11 +0000] [24] [INFO] Handling signal: term
[2022-10-13 13:56:11 +0000] [26] [INFO] Worker exiting (pid: 26)
[2022-10-13 13:56:11 +0000] [25] [INFO] Worker exiting (pid: 25)
[2022-10-13 13:56:12 +0000] [24] [INFO] Shutting down: Master
```

devcontainer.json

```json
{
	"name": "Airflow",
	"dockerComposeFile": "../../docker-compose.yml",
	"service": "airflow_webserver",
	"runServices": ["airflow_init", "airflow_webserver", "airflow_scheduler", "airflow_worker"],
	"remoteUser": "root",
	"workspaceFolder": "/opt/airflow",
	"extensions": [
		"ms-python.python",
		"eamodio.gitlens",
		"GitHub.vscode-pull-request-github",
		"njpwerner.autodocstring",
		"DavidAnson.vscode-markdownlint"
	],
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash",
		"python.pythonPath": "/var/lang/bin/python",
		"python.linting.enabled": true,
		"python.linting.pylintEnabled": true,
		"python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
		"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
		"python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
		"python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
		"python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
		"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
		"python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
		"python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
        "python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
        "python.testing.unittestEnabled": false,
        "python.testing.nosetestsEnabled": false,
		"python.testing.pytestEnabled": true,
		"yaml.format.enable": true,
		"githubPullRequests.queries": [
			{
				"label": "Waiting For My Review",
				"query": "is:open review-requested:${user}"
			},
			{
				"label": "Assigned To Me",
				"query": "is:open assignee:${user}"
			},
			{
				"label": "Created By Me",
				"query": "is:open author:${user}"
			},
			{
				"label": "Mentioned Me",
				"query": "is:open mentions:${user}"
			}
		],
		"githubIssues.queries": [
			{
				"label": "Current Iteration",
				"query": "project:company/2 assignee:${user} sort:created-desc label:current"
			}
		]
	},
	"postAttachCommand": "sudo chmod o=rwx /var/run/docker.sock && git config core.filemode false",
}
```

docker-compose.yml

```yaml
version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ./airflow/
    dockerfile: Dockerfile.dev
    args:
      - PYTHONUNBUFFERED=1
      - PYPIPASS=${PYPIPASS}
      - PYPIUSER=${PYPIUSER}
      - AIRFLOW_VERSION=2.2.2
      - PYTHON_VERSION_SHORT=3.8
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow_postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@airflow_redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true' # https://github.com/apache/airflow/issues/13487
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'Europe/Berlin'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Europe/Berlin'
    AIRFLOW__LOGGING__LOGGING_CONFIG_CLASS: 'dags.settings.LOGGING_CONFIG'
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    HOST_HOME: ${HOME}
    PYTHONPATH: '/opt/airflow'
    ENVIRONMENT: 'dev'
    USES_PYDOC: 'true'
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/.git:/opt/airflow/.git
    - ./airflow/.gitignore:/opt/airflow/.gitignore
    - ./airflow/.gitmodules:/opt/airflow/.gitmodules
    - ./airflow/.devcontainer:/opt/airflow/.devcontainer
    - ./airflow/.docusaurus:/opt/airflow/.docusaurus
    - ./airflow/.docs:/opt/airflow/.docs
    - ./airflow/.circleci:/opt/airflow/.circleci
    - ./airflow/requirements.txt:/opt/airflow/requirements.txt
    - ./airflow/requirements_dev.txt:/opt/airflow/requirements_dev.txt
    - ./airflow/pydoc-markdown.yml:/opt/airflow/pydoc-markdown.yml
    - ./airflow/README.md:/opt/airflow/README.md
    - ./airflow/fargate_entrypoint.sh:/opt/airflow/fargate_entrypoint.sh
    - ./airflow/sync_dags.sh:/opt/airflow/sync_dags.sh
    - ./airflow/.vscode:/opt/airflow/.vscode
    - ./airflow/Dockerfile:/opt/airflow/Dockerfile
    - ./airflow/Dockerfile.dev:/opt/airflow/Dockerfile.dev
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp:/tmp # https://github.com/apache/airflow/issues/16803#issuecomment-874246604
  user: '$AIRFLOW_UID:$AIRFLOW_GID'
  networks:
    - localstack_nw
    - airflow_nw
  depends_on:
    airflow_redis:
      condition: service_healthy
    airflow_postgres:
      condition: service_healthy
    localstack:
      condition: service_started
    db:
      condition: service_started

services:
  db:
    container_name: company_db
    image: mdillon/postgis:10
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - POSTGRES_USER=company_master
      - POSTGRES_PASSWORD=8CGc4PpQT3lpd8sG4p5K
      - POSTGRES_DB=company
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    networks:
      - db_nw
      - db_pgadmin_nw
      - localstack_nw

  localstack:
    container_name: company_localstack
    image: localstack/localstack:0.14.3
    environment:
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: 1
      # DATA_DIR: /tmp/localstack/data
      HOST_TMP_FOLDER: /tmp/localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LAMBDA_REMOTE_DOCKER: 0
      LAMBDA_STAY_OPEN_MODE: 0
      LAMBDA_DOCKER_FLAGS: -p 19891:19891
      LAMBDA_DOCKER_NETWORK: company_localstack_nw
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${HOME}/_company/company/services/qgis:${HOME}/_company/company/services/qgis"
    networks:
      - localstack_nw

  airflow_redis:
    container_name: company_airflow_redis
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - airflow_nw

  airflow_postgres:
    container_name: company_airflow_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflowdata:/var/lib/postgresql/data
    networks:
      - airflow_nw
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5

  airflow_webserver:
    <<: *airflow-common
    container_name: company_airflow_webserver
    command: webserver
    ports:
      - 9080:8080
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow_init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-company}

  airflow_scheduler:
    <<: *airflow-common
    container_name: company_airflow_scheduler
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"'
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow_worker:
    <<: *airflow-common
    container_name: company_airflow_worker
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  dbdata: {}
  airflowdata: {}

networks:
  db_nw:
    driver: bridge
  db_pgadmin_nw:
    driver: bridge
  localstack_nw:
    driver: bridge
  mailhog_nw:
    driver: bridge
  airflow_nw:
    driver: bridge
```

To explain: The devcontainer is connected to the airflow_webserver service but also starts the other airflow services. For some reason, it is only the airflow_worker container that experiences the issue with the .pid file. My hunch is that when the devcontainer is closed, the airflow_worker container is not properly stopped. I submit this issue with to the repo of the dev container extension since this issue does not happen, when I start the containers with `docker-compose up` and close with `docker-compose down`. I previously looked at https://stackoverflow.com/a/37549262 to get the idea with `docker-compose down`. Thats when I realized the issue might lie with the devcontainer since it does not seem to execute `docker-compose down` when closing. Maybe add an option for that?

I would gladly recieve any help even just a hint in the right direction to solve this problem. Maybe someone had to deal with something similar in the past. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
We use `docker-compose stop -t 0` after a timeout. Does adding `"shutdownAction": "none"` to the devcontainer.json work around the problem? (The containers will keep running.)

**Comment by selim-seyhanoglu** [comment]
I tried adding `"shutdownAction": "none"` and then manually stopping the containers. I ran into the same problem when executing `docker-compose stop -t 0` but not with `docker-compose stop`. The default timeout is 10 seconds, so apparently the zero timeout causes the airflow_worker service to stop improperly. Is there a way to add a custom shutdown timeout in the devcontainer.json maybe?

**Comment by selim-seyhanoglu** [comment]
So I eventually found a satisfying solution to get around this issue. I mounted the airflow worker to a temporary file system and I only changed two lines in the docker compose file under the airflow worker:

```
airflow_worker:
    <<: *airflow-common
    # start
    tmpfs:
      - '/opt/airflow/'
    # end
    container_name: company_li_airflow_worker
    command: celery worker
    healthcheck:
```
