### ISSUE TITLE
Java debugger ignores xhtml files in remote enviorement

### ISSUE THREAD

**Issue by Help3rL** [microsoft/vscode-remote-release#7399]
- VSCode Version: 1.72.2
- Local OS Version: Windows 10 (19044.2006)
- Remote OS Version: mcr.microsoft.com/devcontainers/java:8-buster
- Remote Extension/Connection Type: Containers
- Logs: No error log

Docker file: 
``` yml
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/java/.devcontainer/base.Dockerfile
# [Choice] Java version (use -bullseye variants on local arm64/Apple Silicon): 8, 11, 17, 8-bullseye, 11-bullseye, 17-bullseye, 8-buster, 11-buster, 17-buster
ARG VARIANT=8-bullseye
FROM mcr.microsoft.com/devcontainers/java:${VARIANT}

# [Option] Install Maven
ARG INSTALL_MAVEN="false"
ARG MAVEN_VERSION=""
# [Option] Install Gradle
ARG INSTALL_GRADLE="false"
ARG GRADLE_VERSION=""
RUN if [ "${INSTALL_MAVEN}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/sdkman/bin/sdkman-init.sh && sdk install maven \"${MAVEN_VERSION}\""; fi \
    && if [ "${INSTALL_GRADLE}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/sdkman/bin/sdkman-init.sh && sdk install gradle \"${GRADLE_VERSION}\""; fi

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    # && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
```
Docker compose: 
``` yml
version: '3.8'
services:
  db:
    image: mariadb:10.10-rc
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: vspn
      MYSQL_ROOT_PASSWORD: 9VhOGz86DgdxLvUIbA09qCG3kVN7
    volumes:
      - dev-data:/var/lib/mysql
      # - ./dumpFreshDB.sql:/docker-entrypoint-initdb.d/dumpFreshDB.sql #For dumping all nessesary DB info before inicializing application (might cause errors)
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 6858:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
  application:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VARIANT: 8-buster
        INSTALL_MAVEN: true
        MAVEN_VERSION: 3.8.6
        INSTALL_GRADLE: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vspn?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '9VhOGz86DgdxLvUIbA09qCG3kVN7'
    volumes:
      - ..:/workspace
    working_dir: /workspace
volumes:
  dev-data:
    name: dev-data
```
devcontainer.json : 
``` json
{
	"name": "VSPN",
	"dockerComposeFile": "docker-compose.yml",
	"service": "application",
	"workspaceFolder": "/workspace",
	"settings": {
	  "maven.executable.path": "/usr/local/sdkman/candidates/maven/current/bin/mvn"
	},
	"overrideCommand": true,
	"extensions": [
	  "vscjava.vscode-java-pack",
	  "svipas.prettier-plus",
	  "mtxr.sqltools",
	  "VisualStudioExptTeam.intellicode-api-usage-examples",
		"loiane.java-spring-extension-pack"
	],
	"remoteUser": "vscode",
	"forwardPorts": [8080]
  }
```

Steps to Reproduce:

1. Launch vscode remote container
2. Start java debugger
3. Edit xhtml file
4. Reload page to see changes (not happening(localy when trying works fine))

###Tried:

- checking on others computers (total tested 9 works on 1) 
- checking versions (docker, docker-engine,docker compose, vscode, windows,java, java-debugger, maven compiler, spring boot, and so on ... ) 
- updating versions and switching java versions in docker envioremnt (devContainer) 
- chaging compiler to JRebel
- using other OsSystem (Ubuntu)
- changing compose to be centered on ubuntu dev envioremnt.
- Installing and reinstalling vscode extencions
- checking all configs (besides windows settings)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
