### ISSUE TITLE
Multiple containers not working as expected

### ISSUE THREAD

**Issue by labmonkey42** [microsoft/vscode-remote-release#7521]
- VSCode Version: 1.73.1
- Local OS Version: Ubuntu 22.04.1 LTS
- Remote Extension/Connection Type: Remote Containers

Following [documentation](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers) slightly modified, I have a repository structure similar to the following:
```
myrepo
├── .devcontainer
│   ├── devcontainer.json
│   └── docker-compose.devcontainer.yaml
├── myapp
│   └── .devcontainer
│       └── devcontainer.json
└── lib
    └── mylib
        └── .devcontainer
            └── devcontainer.json
```

`myrepo/.devcontainer/docker-compose.devcontainer.yaml`:
```YAML
version: '3'
services:
  myapp:
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: myrepo-lib-mylib
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:16
    user: node
    volumes:
      - ../:/home/node/myrepo:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # ...
  mylib:
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: myrepo-myapp
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:16
    user: node
    volumes:
      - ../:/home/node/myrepo:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # ...
  myrepo:
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: myrepo-lib-mylib
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
    # ...
    volumes:
      ../:/home/vscode/myrepo:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # ...
```

`myrepo/.devcontainer/devcontainer.json`:
```JSON
{
    "dockerComposeFile": "docker-compose.devcontainer.yaml",
    "name": "myrepo",
    "remoteUser": "vscode",
    "service": "myrepo",
    "shutdownAction": "stopCompose",
    "workspaceFolder": "/home/vscode/myrepo"
}
```

`myrepo/myapp/.devcontainer/devcontainer.json`:
```JSON
{
    "dockerComposeFile": "../../.devcontainer/docker-compose.devcontainer.yaml",
    "name": "myrepo-myapp",
    "remoteUser": "node",
    "service": "myapp",
    "shutdownAction": "none",
    "workspaceFolder": "/home/node/myrepo/myapp"
}
```

`myrepo/lib/mylib/.devcontainer/devcontainer.json`:
```JSON
{
    "dockerComposeFile": "../../../.devcontainer/docker-compose.devcontainer.yaml",
    "name": "myrepo-lib-mylib",
    "remoteUser": "node",
    "service": "mylib",
    "shutdownAction": "none",
    "workspaceFolder": "/home/node/myrepo/lib/mylib"
}
```

If I leave `myrepo/.devcontainer/devcontainer.json` in place and open the repo root folder in a container and then attach to either of the subproject devcontainers in a separate window and then navigate to open that subproject folder, the `devcontainer.json` for that subproject folder is ignored and my expected extensions are not installed.  If, instead of attaching, I open the subproject folder in a container, it attempts to rebuild the entire composition and fails due to container name conflict rather than detecting the other running container(s).

If I remove `myrepo/.devcontainer/devcontainer.json` and open each of the subproject folders in separate windows in containers everything seems to work as expected, but I lose the ability to manage the greater repository separately and from Explorer.

Am I doing something wrong?  Is this unsupported?  Can it be supported?
