### ISSUE TITLE
Conditional Docker files / docker compose files

### ISSUE THREAD

**Issue by MBAatEJOT** [microsoft/vscode-remote-release#7739]
You can use the devcontainers in a project for several scenarios. Like you can develop in a GH codespace or in a local Docker (Desktop) container. 

Depending on where the devcontainer is running it might be necessary to have a slightly different Dockerfile oder docker-compose file. For example, when developing a project in a GH codespace you might require a additional container/service for the database. The docker-compose file for this scenario might look like this:

```yaml
version: '3'
services:
  app:
    container_name: MyProject
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /var/run/docker.sock:/var/run/docker-host.sock
    - ..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    container_name: MyProjectDB
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      COLLATION: Latin1_General_CI_AS
      SA_PASSWORD: SomePasswordHere
```` 

But when you are developing the same project in a local container using Docker Desktop, you might don't require the `db` service because there is already a local SQLServer running on your machine.

So it would be great to tell the container build process to use another `docker-compose` file which doesn't contain the additional `db` service:

```yaml
version: '3'
services:
  app:
    container_name: MyProject
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /var/run/docker.sock:/var/run/docker-host.sock
    - ..:/workspaces:cached
    - shareddata:/tmp/host
    network_mode: host
    command: sleep infinity

volumes: # instead of the db service it mounts an external folder to share data between container and host
  shareddata:
    external: true

```

Maybe this could be done by using conditions when analysing the `devcontainer.json`. 

For example like this:
```json
{
	"dockerComposeFile": "$IS_CODESPACE == yes ? docker-compose-codespace.yml : docker-compose.yml",
	"service": "app",
	"workspaceFolder": "/workspaces",
	"remoteEnv": {
		"LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}",
		"IS_CODESPACE": "${localEnv:IS_CODESPACE}"
	},
	"name": "MyProject"
}
```

```json
{
	"dockerComposeFile": {
		"codespaces": {
			"envVar": "IS_CODESPACE",
			"equals": "yes",
			"file": "docker-compose-codespace.yml"
		},
		"default": {
			"file": "docker-compose.yml"
		}
	},
	"service": "app",
	"workspaceFolder": "/workspaces",
	"remoteEnv": {
		"LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}",
		"IS_CODESPACE": "${localEnv:IS_CODESPACE}"
	},
	"name": "MyProject"
}
```

Or in whatever form this could be implemented.
