### ISSUE TITLE
devcontainer does not work with generated files

### ISSUE THREAD

**Issue by shokkunrf** [microsoft/vscode-remote-release#7946]
- VSCode Version: 1.74.3 , 1.75.0-insider
- Local OS Version: Linux x64 4.19.0-23-amd64 (Debian buster)
- Remote Extension/Connection Type: Containers
- Logs: Workspace does not exist

Steps to Reproduce:
1. From `Open a Remote Window`
2. Select `Add Devcontainer Configuration Files... `
3. Select `FROM 'docker-compose.yml'`
4. Do not select `Select additional features to install`
5. `./.devcontainer/devcontainer.json` and `./.devcontainer/docker-compose.yml` are generated

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

---
## Steps to Reproduce
Select `Add Devcontainer Configuration Files... `, select `FROM 'docker-compose.yml'`, and do not select `Select additional features to install` generates the following `./.devcontainer/devcontainer.json` and `./.devcontainer/docker-compose.yml`.

- `./.devcontainer/devcontainer.json`
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/docker-existing-docker-compose
{
	"name": "Existing Docker Compose (Extend)",

	// Update the 'dockerComposeFile' list if you have more compose files or use different names.
	// The .devcontainer/docker-compose.yml file contains any overrides you need/want to make.
	"dockerComposeFile": [
		"../docker-compose.yml",
		"docker-compose.yml"
	],

	// The 'service' property is the name of the service for the container that VS Code should
	// use. Update this value and .devcontainer/docker-compose.yml to the real service name.
	"service": "app",

	// The optional 'workspaceFolder' property is the path VS Code should open by default when
	// connected. This is typically a file mount in .devcontainer/docker-compose.yml
	"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}"

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Uncomment the next line if you want start specific services in your Docker Compose config.
	// "runServices": [],

	// Uncomment the next line if you want to keep your containers running after VS Code shuts down.
	// "shutdownAction": "none",

	// Uncomment the next line to run commands after the container is created.
	// "postCreateCommand": "cat /etc/os-release",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as an existing user other than the container default. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "devcontainer"
}
```

- `./.devcontainer/docker-compose.yml`
```yml
version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```

## Problems
- `./.devcontainer/devcontainer.json` 
By the following item, running devcontainer will show an error `Workspace does not exist`.
```json
"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}"
```

- `./.devcontainer/docker-compose.yml`
By the following item, it will mount the directory above the project root directory.
```yml
volumes
    - ../..:/workspaces:cached
```

## Solutions
This problems can be resolved this way.
- `./.devcontainer/devcontainer.json`
```diff
- "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}"
+ "workspaceFolder": "/workspaces"
```

- `./.devcontainer/docker-compose.yml`
```diff
volumes
-   - ../..:/workspaces:cached
+   - .:/workspaces:cached
```

Is it possible to revert the generated files to their pre-update state like Solutions?

(Maybe it has something to do with this issue?: https://github.com/microsoft/vscode-remote-release/issues/7686#issuecomment-1346738274 )

**Comment by chrmarti** [comment]
Would keeping the devcontainer.json as-is and changing the mount point to `- ..:/workspaces:cached` work for you? We chose these in a way that should make it also work with the `Clone in Volume` setup.

**Comment by shokkunrf** [comment]
Thank you for your reply.
Yes. I kept the devcontainer.json as-is and changed the mount point to `- ..:/workspaces:cached` and it worked.

**Comment by shokkunrf** [comment]
Thank you.

**Comment by chrmarti** [comment]
Steps to verify:
- Add a `docker-compose.yml` to a workspace's root folder:
```
version: '3.9'
services:
  devcontainer:
    image: debian:latest
```
- Run "Add Dev Container Configuration Files..." and pick the docker-compose.yml.
- Reopen folder in dev container and verify the Explorer shows the workspace folder and its files.
