### ISSUE TITLE
Dev Containers v0.275.1: "build: ." or "context: ." syntax prohibits VS Code from being opened in remote container --> maybe prefer `docker compose` over `docker-compose`, if both methods are available on a system

### ISSUE THREAD

**Issue by thomiel** [microsoft/vscode-remote-release#8059]
Reason: the . or ./folder notation leads to the extension trying to open the Dockerfile in /home/<user>/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/ .

- VSCode Version: 1.75.1
- Local OS Version: Ubuntu 20.04.1LTS (Kernel 5.15.0-60-generic)
- Remote OS Version:
- Remote Extension/Connection Type: Containers

- Logs:

`Error: ENOENT: no such file or directory, open .vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/Dockerfile`

Steps to Reproduce:

1. add Dockerfile: 
`FROM postgres:13 AS database`
3. add docker-compose.yml:
```
services:
  database:
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: test
```
4. Reopen in Remote Container

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

Workaround: copying the Dockerfile into the Extension folder (sic!)... changing the . to "." in the .yml sometimes works as well.

```
services:
  database:
    build:
      context: "."
    environment:
      POSTGRES_PASSWORD: test
```
