### ISSUE TITLE
[remote-tunnel] Add ability to persist authentication when running in docker

### ISSUE THREAD

**Issue by SelfhostedPro** [microsoft/vscode-remote-release#8358]
I've put together a dockerfile to deploy vscode-cli into a container and initialize a tunnel in order for me to connect and work inside of it easily. 

```docker

FROM lsiobase/alpine:3.17

RUN apk add --no-cache git curl docker nodejs-lts openssh alpine-zsh-config && \
    curl -sL "https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64" \
        --output /tmp/vscode-cli.tar.gz && \
    tar -xf /tmp/vscode-cli.tar.gz -C /usr/bin && \
    rm /tmp/vscode-cli.tar.gz && \
    rm -rf \
	    /root/.cache \
	    /tmp/*

CMD [ "code", "tunnel", "--accept-server-license-terms" ]
```

One issue I'm running into is that every time the container restarts I have to reauthorize the device which makes it a bit difficult to persist. Is there a specific folder the authentication persists in that I could mount to the host so that when the container restarts I don't have to reauth?

**Comment by connor4312** [comment]
Setting the environment variable `VSCODE_CLI_USE_FILE_KEYCHAIN` will cause the token to be stored in `~/.vscode-cli`, which you could persist however you'd like. We can document this.

**Comment by geilmaker** [comment]
Hey :)
I have the same problem, I created a Docker Image myself for vscode server, but everytime the container is recreated I need to authenticate via github.

My docker-compose.yml
```yaml
version: '3'

services:
  vscode-server:
    image: sw/vscode-server
    container_name: vscode-server
    restart: always
    user: "1002:1002"
    volumes:
      - ./.vscode-cli:/vscode-server/.vscode-cli
      - ./.vscode-server:/vscode-server/.vscode-server
      - ./.vscode-tmp:/tmp
      - ./data:/vscode-server/workspace
    environment:
      VSCODE_CLI_USE_FILE_KEYRING: true
    networks:
      - vscode

networks:
  vscode:
    external: true
```

I guess most important are the volumes and environment variables. As you told in your answer, I set the `VSCODE_CLI_USE_FILE_KEYRING` environment variable and I make the `.vscode-cli` directory persistent. But it is still not working currently - maybe you can give me a hint what I might do wrong? :)

Cheers!

**Comment by markhuang1212** [comment]
I met the same issue when trying to setup vscode tunnel inside container. Making the host name consistent across container creation seems to solve the problem for me.

**Comment by da-wilky** [comment]
Do you mean setting a container name? Unfortunatly thats not working in my case, as I set the `container_name: vscode-server`... Or do you mean something else and I misunderstand?

**Comment by da-wilky** [comment]
Ofc I misunderstood it. There is a property in dockercompose `hostname: xxx`. Using this I don't need to relogin every time. Thx.
...even working without the `VSCODE_CLI_USE_FILE_KEYRING`.

**Comment by Justin1904** [comment]
how does one make use of the token once it's persisted though? here's what i did which didn't work:

1. I ran `VSCODE_CLI_USE_FILE_KEYRING=1 code tunnel`, selected Github as the authentication provider, and did the interactive device login
2. I got the file at `~/.vscode/cli/token.json`, in it I found a token
3. I then ran `code tunnel user logout` to logout and want to test auth with token
4. I ran `code tunnel user login --provider github --access-token <my-token-in-step-2>`, this step didn't produce any logs
5. I ran `code tunnel` and got the following
![image](https://github.com/microsoft/vscode-remote-release/assets/18243483/47b6daf1-4f76-4172-804a-791ac7a38b7a)

So in the end this does not seem to work for me. Wonder if I'm doing something wrong here?

**Comment by da-wilky** [comment]
My container just runs `code tunnel` to start the vscode server. Then I get a few digits I need to enter on a specific link (github) to authenticate the application. After doing so, some files get created in the folder. With the volumes I persist them, so after a container recreation I have the same files, that authenticate me automatically when running `code tunnel`. I do nt login/logout or anything.

**Comment by rishabh-dream11** [comment]
@connor4312 The solution specified doest seem to solve the problem fully,  even after setting the environment variable, it asks for authentication after restart.

**Comment by da-wilky** [comment]
Im not using it anymore but this was the working solution for me:

```yml
# version: '3'  # Not needed anymore

services:
  vscode-server:
    image: sw/vscode-server # My own image thats not uploaded - replace it with yours
    container_name: vscode-server
    hostname: vscode # That made the key for persisting my github login over the container lifecycle
    restart: always
    user: "1002:1002" # Choose the right user for you
    volumes:
      - ./.vscode-cli:/vscode-server/.vscode-cli
      - ./.vscode-server:/vscode-server/.vscode-server
      - ./.vscode-tmp:/tmp
      - ./data:/vscode-server/workspace
    networks:
      - vscode # If you want to connect to other containers use the network

networks:
  vscode:
    external: true # Need to be created before starting the container with 'docker network create vscode'
```

Have a good one!
