### ISSUE TITLE
Container Build Failed - An error occurred setting up the container.

### ISSUE THREAD

**Issue by hamad-9** [microsoft/vscode-remote-release#8450]
Hi there,

Since the beginning of this year, I have been using the Dev Container extension, and everything has been fine. I used to use the "Rebuild and Reopen in Container" command, and I significantly depended on Dev containers in my development workflow since many project dependencies cannot be installed on my local machine.

However, my work is currently blocked due to a problem that I do not know how to solve. The first time the problem occurred, the container started in VSCode, and everything seemed fine except that the extensions inside the container were not working, including the Python extension.

I have tried everything, including reinstalling the Dev Container extension, Docker, and VSCode. I don't know what to do. I even rolled back my work to an older version that I am 100% sure was fine, but I am still facing the same problem.

The major problem is that there are no logs available, so I can't see why the extensions are not working. I also ran the "python manage.py runserver 0.0.0.0:8000" command inside the terminal in the Dev container, and it worked. So, the Dev container is working, but the extensions are not, and there are no logs available to diagnose the actual problem.

The last thing I did was reset my Mac to factory settings and format it. However, I am now facing a new problem; the container build failed when I ran the "Rebuild and Reopen in Container" command, and these are the logs that occurred.

**#Error**
[2713 ms] Container server: Error relocating /root/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
[2714 ms] Container server: Error relocating /root/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
[2761 ms] Error: stream ended with:0 but wanted:9
        at c (/Users/hamad/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/extension/extension.js:24:101670)
        at /Users/hamad/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/extension/extension.js:24:101851
        at s (/Users/hamad/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/extension/extension.js:27:5371)
        at Socket.<anonymous> (/Users/hamad/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/extension/extension.js:27:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1358:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2761 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-9d576356-f54c-47e9-a15b-abc68efb705e1683318430269' && cat > '/tmp/devcontainers-9d576356-f54c-47e9-a15b-abc68efb705e1683318430269/env-loginInteractiveShell.json' << 'envJSON'
[2762 ms] Container server terminated (code: 127, signal: null).
[2765 ms] 
[2765 ms] 
[2769 ms] Command failed: /root/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-252e5463d60e63238250799aef7375787f68b4ee --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
[2769 ms] Error relocating /vscode/vscode-server/bin/alpine-arm64/252e5463d60e63238250799aef7375787f68b4ee/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /vscode/vscode-server/bin/alpine-arm64/252e5463d60e63238250799aef7375787f68b4ee/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
[2769 ms] Exit code 127

**docker-compose.yml**
```
version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name:  postgres
    ports:
      - "8001:5432"
    expose:
      - 5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
```

**DockerFile**
```
FROM python:3.9-alpine3.13
LABEL maintainer="Hamad Numan"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./requirements.dev.txt /tmp/requirements.dev.txt
COPY ./api /api
WORKDIR /api
EXPOSE 8000

ARG DEV=false
RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ $DEV = "true" ]; \
        then /py/bin/pip install -r /tmp/requirements.dev.txt ; \
    fi && \
    rm -rf /tmp && \
    apk del .tmp-build-deps

ENV PATH="/py/bin:$PATH"
```

**Macbook pro m1 pro**
**MacOs 13.3.1**
