### ISSUE TITLE
Cannot reopen in dev containers

### ISSUE THREAD

**Issue by monolith-codes** [microsoft/vscode-remote-release#8500]
- VSCode Version: 1.79.0 (insider)
- Local OS Version: Ubuntu 22.04.2 LTS (WSL2)
- Remote OS Version: Node18 Docker Image
- Remote Extension/Connection Type: Containers

- Logs:
```
[3808 ms] Dev Containers 0.293.0 in VS Code 1.79.0-insider (f1258a5fbed44b8f84a097c73c1799c13c5c3646).
[3808 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/monolith/Studium/FullStackWeb/webshop-server' && /bin/sh
[3826 ms] Start: Run in host: id -un
[3916 ms] monolith
[3917 ms] 
[3917 ms] Start: Run in host: cat /etc/passwd
[3919 ms] Start: Run in host: echo ~
[3923 ms] /home/monolith
[3923 ms] 
[3924 ms] Start: Run in host: test -x '/home/monolith/.vscode-remote-containers/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node'
[3925 ms] 
[3925 ms] 
[3925 ms] Exit code 1
[3926 ms] Start: Run in host: test -x '/home/monolith/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node'
[3927 ms] 
[3927 ms] 
[3927 ms] Start: Run in host: test -f '/home/monolith/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node_modules/node-pty/package.json'
[3928 ms] 
[3928 ms] 
[3928 ms] Start: Run in host: test -f '/home/monolith/.vscode-remote-containers/dist/vscode-remote-containers-server-0.293.0.js'
[3929 ms] 
[3929 ms] 
[3931 ms] userEnvProbe: loginInteractiveShell (default)
[3932 ms] userEnvProbe: not found in cache
[3932 ms] userEnvProbe shell: /bin/bash
[5935 ms] Start: Run in Host: /bin/sh 
[5939 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[6198 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  14377: /bin/bash -lic echo -n 18951387-7c90-47fa-b6ce-f04789de6a7a; cat /proc/self/environ; echo -n 18951387-7c90-47fa-b6ce-f04789de6a7a 
    14572: /bin/bash -lic echo -n 18951387-7c90-47fa-b6ce-f04789de6a7a; cat /proc/self/environ; echo -n 18951387-7c90-47fa-b6ce-f04789de6a7a 
      14573: ng completion script                                                                                
[13946 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.
[14000 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/monolith/Studium/FullStackWeb/webshop-server' && /bin/sh
[14019 ms] Start: Run in host: id -un
[14117 ms] monolith
[14117 ms] 
[14118 ms] Start: Run in host: cat /etc/passwd
[14120 ms] Start: Run in host: echo ~
[14121 ms] /home/monolith
[14122 ms] 
[14122 ms] Start: Run in host: test -x '/home/monolith/.vscode-remote-containers/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node'
[14123 ms] 
[14123 ms] 
[14123 ms] Exit code 1
[14123 ms] Start: Run in host: test -x '/home/monolith/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node'
[14124 ms] 
[14125 ms] 
[14125 ms] Start: Run in host: test -f '/home/monolith/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node_modules/node-pty/package.json'
[14126 ms] 
[14126 ms] 
[14126 ms] Start: Run in host: test -f '/home/monolith/.vscode-remote-containers/dist/vscode-remote-containers-server-0.293.0.js'
[14128 ms] 
[14128 ms] 
[14129 ms] userEnvProbe: loginInteractiveShell (default)
[14129 ms] userEnvProbe: not found in cache
[14129 ms] userEnvProbe shell: /bin/bash
[16138 ms] Start: Run in Host: /bin/sh 
[16142 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[16389 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  15183: /bin/bash -lic echo -n 420cc91f-4b08-4d0b-bbbd-df358300f182; cat /proc/self/environ; echo -n 420cc91f-4b08-4d0b-bbbd-df358300f182 
    15378: /bin/bash -lic echo -n 420cc91f-4b08-4d0b-bbbd-df358300f182; cat /proc/self/environ; echo -n 420cc91f-4b08-4d0b-bbbd-df358300f182 
      15379: ng completion script                                                                                
[24136 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.
[24176 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[24234 ms] 1.42
[24278 ms] Start: Run in Host: /home/monolith/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node /home/monolith/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/monolith/Studium/FullStackWeb/webshop-server --log-level debug --log-format json --config /home/monolith/Studium/FullStackWeb/webshop-server/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true --terminal-columns 316 --terminal-rows 77
[24439 ms] @devcontainers/cli 0.41.0. Node.js v16.17.1. linux 5.15.90.1-microsoft-standard-WSL2 x64.
[24439 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/monolith/Studium/FullStackWeb/webshop-server --filter label=devcontainer.config_file=/home/monolith/Studium/FullStackWeb/webshop-server/.devcontainer/devcontainer.json
[24494 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/monolith/Studium/FullStackWeb/webshop-server
[24550 ms] Start: Run: docker-compose version --short
[24553 ms] Error: Command failed: docker-compose version --short
    at Jc (/home/monolith/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:1946:867)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async G7 (/home/monolith/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:1874:22374)
    at async Pae (/home/monolith/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:2092:34312)
[24557 ms] Exit code 1
```

**Steps to Reproduce:**

1. Using the option reopen in dev containers via dev containers extension

When i try to reopen the project in dev containers via the extension, the startup fails with this logs. On another machine with same WSL setup it works fine. I provide the project folder structure and the docker files below:

![folderstructure](https://github.com/microsoft/vscode-remote-release/assets/86384864/d5ef56e4-464e-4ec9-b472-887bd1301a84)

**.devcontainer/devcontainer.json:**

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/docker-existing-docker-compose
{
    "name": "Webshop API",

    // Update the 'dockerComposeFile' list if you have more compose files or use different names.
    // The .devcontainer/docker-compose.yml file contains any overrides you need/want to make.
    "dockerComposeFile": ["../docker-compose.yml", "docker-compose.yml"],

    // The 'service' property is the name of the service for the container that VS Code should
    // use. Update this value and .devcontainer/docker-compose.yml to the real service name.
    "service": "api",

    // The optional 'workspaceFolder' property is the path VS Code should open by default when
    // connected. This is typically a file mount in .devcontainer/docker-compose.yml
    "workspaceFolder": "/app",
    "customizations": {
        "vscode": {
            "extensions": ["GitHub.copilot", "eamodio.gitlens", "esbenp.prettier-vscode", "ms-azuretools.vscode-docker"]
        }
    }

    // Features to add to the dev container. More info: https://containers.dev/features.
    // "features": {},

    // Use 'forwardPorts' to make a list of ports inside the container available locally.
    // "forwardPorts": [8080]

    // Uncomment the next line if you want start specific services in your Docker Compose config.
    // "runServices": [],

    // Uncomment the next line if you want to keep your containers running after VS Code shuts down.
    // "shutdownAction": "none",

    // Uncomment the next line to run commands after the container is created.
    // "postCreateCommand": "cat /etc/os-release",

    // Uncomment to connect as an existing user other than the container default. More info: https://aka.ms/dev-containers-non-root.
    // "remoteUser": "devcontainer"
}
```

**.devcontainer/docker-compose.yml:**

```
version: '3.8'
services:
  api:
    build:
      context: .
      target: "dev"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev```
    
    ./docker-compose.yml: 
    
    ```services:
  api:
    build:
      context: .
      target: "prod"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    volumes:
      - "mariadb:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  mariadb:
  ```
  
  **./docker-compose.yml**
  ```
services:
  api:
    build:
      context: .
      target: "prod"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    volumes:
      - "mariadb:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  mariadb:

  ```
  
  **./Dockerfile:**
  
  ```
FROM node:18 as base

FROM base as dev

WORKDIR /app

COPY package*.json ./
RUN npm install

FROM base as prod

WORKDIR /app

COPY . .

RUN npm cache clean --force
RUN npm install
RUN npm run build

CMD [ "node", "build/index.js" ]

EXPOSE 8080
```
