### ISSUE TITLE
Devcontainer: Allow VSCode Browser to Access Applications in Docker Network

### ISSUE THREAD

**Issue by CodeMan99** [microsoft/vscode-remote-release#8542]
## Example Use Case

I have a _docker-compose_ based devcontainer where one of the sidecar services is [datalust/seq](https://hub.docker.com/r/datalust/seq) for logging.

### Compose Definition

In my full application there are five services (app, seq, postgres x 2, & seq-input-gelf). I'll include just the relevant services here.

```yaml
version: '3.8'

services:
    app:
        image: mcr.microsoft.com/devcontainers/dotnet:0-7.0-bullseye
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
        hostname: warehouse
        networks:
            qubitnet:
                ipv4_address: 172.16.240.2
        env_file: devcontainer.env

    seqlogging:
        image: datalust/seq:2023.1
        restart: unless-stopped
        hostname: seqsvr
        networks:
            qubitnet:
                ipv4_address: 172.16.240.5
        ports:
            - "8005:80"
        volumes:
            - seqlogging-data:/data
        environment:
            ACCEPT_EULA: "Y"

volumes:
    seqlogging-data:

networks:
    qubitnet:
        ipam:
            config:
                - subnet: 172.16.240.0/24
                  gateway: 172.16.240.1
```

## Current Behavior

1. Open the "simple browser".
2. Attempt to navigate to `http://seqsvr:80/`.
3. The browser fails to load with error `net::ERR_NAME_NOT_RESOLVED`.

### Expectation

I would expect that to resolve since `curl` has no trouble from the VSCode terminal.

```shell
$ curl --head --include http://seqsvr:80/
HTTP/1.1 200 OK
Content-Length: 8792
Content-Type: text/html
Date: Fri, 26 May 2023 14:19:33 GMT
Accept-Ranges: bytes
Cache-Control: no-store
Expires: Tue, 01 Jan 1980 1:00:00 GMT
Pragma: no-cache
Content-Security-Policy: default-src 'self'; frame-src 'self'; frame-ancestors 'none'; connect-src 'self' ws:; img-src 'self' https: blob:; style-src 'self' 'unsafe-inline'; script-src 'self';
X-Content-Type-Options: nosniff
X-Robots-Tag: noindex,nofollow
```
