### ISSUE TITLE
An odd bind-mount error with "Clone Repository in Container Volume" feature

### ISSUE THREAD

**Issue by gremo** [microsoft/vscode-remote-release#8870]
- VSCode Version: 1.81.1
- Local OS Version: Windows 11
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers

- Logs:

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/workspaces/vscode-remote-try-symfony-sail/config/docker/Caddyfile" to rootfs at "/etc/caddy/Caddyfile": mount /workspaces/vscode-remote-try-symfony-sail/config/docker/Caddyfile:/etc/caddy/Caddyfile (via /proc/self/fd/9), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

Steps to Reproduce:

1. Visit the example repository: https://github.com/gremo/vscode-remote-try-symfony-sail
2. Click on the **Dev containers: open** button

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Seems there is some issue with bind-mounts when using the Clone Repository in Container Volume. The strange thing is that **the error occurs only for the `caddy` service** and NOT for the other bind mounts ([source file](https://github.com/gremo/vscode-remote-try-symfony-sail/blob/main/.devcontainer/docker-compose.dev.yml)):

```yaml
services:
    caddy:
        build:
            target: caddy-dev
        volumes:
            - ../config/docker/Caddyfile:/etc/caddy/Caddyfile:ro # only this mount is triggering the error!
            - ../public/:/srv/public:ro

    php:
        build:
            target: php-dev
        volumes:
            - ../config/docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-app.conf:ro
            - ../config/docker/php.ini:/usr/local/etc/php/conf.d/zz-app.ini:ro

    db:
        build:
            target: mariadb-dev
        volumes:
            - ../config/docker/mariadb.cnf:/etc/mysql/mariadb.conf.d/80-app.cnf:ro
```

Services `php` and `db` starts normally and they are using bind mounts too:

![Immagine 2023-08-21 201506](https://github.com/microsoft/vscode-remote-release/assets/1532616/7a2255de-c1af-4a22-bd75-9625ffde531d)

This is how the `caddy` service file system appears (the read alert occurs when trying to restart the container):

![Immagine 2023-08-21 201526](https://github.com/microsoft/vscode-remote-release/assets/1532616/b1cf8d3b-8845-41d1-ad94-1376169e7187)
