### ISSUE TITLE
Working with multiple devcontainers cannot start one devcontainer: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by juanboterotech** [microsoft/vscode-remote-release#9849]
Trying to use two devcontainers (React and Django) for one project and got an error with each container, found the error previously reported here https://github.com/microsoft/vscode-remote-release/issues/8624

I applied that solution, in my case just changed the local volume in the docker command:

`docker run -it --rm -v ~/.vscode-server:/vscode ubuntu rm -rf /vscode/bin/b58957e67ee1e712cebf466b995adf4c5307b2bd/`

That works for React devcontainer for a moment, the Django container still shows the error when try to reopen:

```
 Start: Run in container: cat '/home/vscode/.vscode-server/bin/b58957e67ee1e712cebf466b995adf4c5307b2bd/product.json'
[6011 ms] SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Kz (c:\Users\juanp\.vscode\extensions\ms-vscode-remote.remote-containers-0.362.0\dist\extension\extension.js:225:1273)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Oue (c:\Users\juanp\.vscode\extensions\ms-vscode-remote.remote-containers-0.362.0\dist\extension\extension.js:221:4028)
        at async Nl (c:\Users\juanp\.vscode\extensions\ms-vscode-remote.remote-containers-0.362.0\dist\extension\extension.js:201:4302)
        at async bpe (c:\Users\juanp\.vscode\extensions\ms-vscode-remote.remote-containers-0.362.0\dist\extension\extension.js:275:6649)
        at async MN (c:\Users\juanp\.vscode\extensions\ms-vscode-remote.remote-containers-0.362.0\dist\extension\extension.js:278:5396)
[6012 ms] /home/vscode
```
My enviroment is:
- VSCode Version: 1.89.0
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu WSL
- Remote Extension/Connection Type: Containers/WSL/Server

I have a docker-compose.yml file which define the containers with some services.

```
version: '3'
services:
  backend:
    container_name: backend
    image: mcr.microsoft.com/devcontainers/python:1-3.9-bullseye
    volumes:
      - .:/workspace:cached
    # Other configuration options for the Python container
    command: sleep infinity
    links:
      - frontend
    environment:
      - TZ=Etc/GMT-5
    networks:
      - mnet

  frontend:
    container_name: frontend
    image: mcr.microsoft.com/devcontainers/typescript-node:0-14
    volumes:
      - .:/workspace:cached
    # Other configuration options for the TypeScript container
    command: sleep infinity
    environment:
      - TZ=Etc/GMT-5
    networks:
      - mnet

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpwd
      - POSTGRES_DB=mydb
    networks:
      - mnet
    ports:
      - 5432:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=radmin
      - RABBITMQ_DEFAULT_PASS=rpassword
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mnet

volumes:
  db-data:
  rabbitmq-data:

networks:
  mnet:
    driver: bridge
```
Also, there is a folder called .devcontainer and inside there is two folders, one called backcontainer which has the devcontainer.json file, the same with the other folder called frontcontainer.
_.devcontainer/backcontainer/devcontainer.json_
```
{
    "name": "Backend",
    "dockerComposeFile": ["../../docker-compose.yml"],
    "service": "backend",
    "shutdownAction": "none",
    "workspaceFolder": "/workspace/backend"
}
```
_.devcontainer/frontcontainer/devcontainer.json_
```
{
    "name": "Frontend",
    "dockerComposeFile": ["../../docker-compose.yml"],
    "service": "frontend",
    "shutdownAction": "none",
    "workspaceFolder": "/workspace/frontend"
}
```
